DemocracyClub/UK-Polling-Stations

polling_stations/apps/data_collection/management/commands/import_westberks.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/pollingstations/migrations/0002_pollingdistrict_polling_station_id.py, polling_stations/apps/pollingstations/models.py
Fixes #106 
This is because sometimes the shapefile contains information
about the actual polling station, and it's not always within
the district itself.
Here's an example:
=> Look up polling station by ID before covers

polling_stations/templates/postcode_view.html
* Strip down the copy (so it’s just the stuff the user needs to know)
* Rearrange stuff on the page a bit (move polling card thing to the right)
* Remove disclaimer when we’re not making any claims to disclaim
* Don’t say “we don’t know” when we’re offering something useful (i.e. the council phone number)
=> Update copy on postcode page

requirements/base.txt
Import scripts depend on ffs - have added it to base requirements.
=> add ffs to base requirements

polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_finder/forms.py, polling_stations/apps/data_finder/views.py, polling_stations/templates/address_select.html, polling_stations/urls.py
Here's the UI mods to allow us to use the data from Denbighshire and RCT. There's quite a few notes/points on this one:
I've modified `BaseAddressCsvImporter` to strip non alphanumeric characters from postcodes when inserting a `ResidentialAddress` object to make this easier to query. If you've already imported Denbighsire and RCT, you'll need to re-run those import scripts.
Having thought this through a bit more clearly, we are going to have to deal with a mix of:
* address data with UPRNs
* full address data without UPRNs (as we've got from RCT)
* partial address data e.g: street name only (as we've got from Denbighsire)
As such, we are going to need to assign each `ResidentialAddress` record its' own internal ID and use that instead of being able to rely on UPRN - so that's the …
=> Add front-end for using ResidentialAddresss data

polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_city_of_london.py, polling_stations/apps/data_collection/management/commands/import_pembrokeshire.py, polling_stations/apps/data_finder/views.py, requirements/base.txt, requirements/testing.txt
Adds:
- base class we can use to import from councils serving up KML boundaries via an API
- import script for City of London
- import script for Pembrokeshire
- some front-end mods to help cope better with ambiguous data
As discussed on slack, this won't provide 100% coverage for Pembrokeshire but will return data in the majority of cases where there is a 1-to-1 mapping between district and station and throw "we don't know where you should vote" in other cases.
Closes #8
Closes #176
refs #175
=> Import scripts for Pembrokeshire and City of London

polling_stations/templates/postcode_view.html
I think the MapQuest style tiles are less confusing, but this could be controversial. User testing required.
Before:
After:
You could also worry about their usage/SLA: http://wiki.openstreetmap.org/wiki/MapQuest#MapQuest-hosted_map_tiles
=> Change to MapQuest tiles

polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/views.py, polling_stations/templates/home.html, polling_stations/templates/postcode_view.html
This is a fairly hacky fix for #103. Currently you get an error if you put in something that looks like a postcode but actually isn't. This adds an exception and a branch in the template.
It should probably do the checking in the form validation code, but currently that'd invoke two postcode lookups, requiring caching. This'll do for a fairly rare error.
=> Add postcode-not-found response, issue #103

polling_stations/templates/postcode_view.html
Initial view now zooms to bounding box of a given route, with the maximum zoom of 16 - so it doesn't get too close in and lose context.
=> Zoom initial view to bounding box of route

polling_stations/apps/data_collection/management/commands/import_boston.py, polling_stations/apps/data_collection/management/commands/import_islington.py, polling_stations/apps/data_collection/management/commands/import_lambeth.py, polling_stations/apps/data_collection/management/commands/import_reading.py, polling_stations/apps/data_collection/management/commands/import_salford.py, polling_stations/apps/data_collection/management/commands/import_south_cambridge.py, polling_stations/apps/data_collection/management/commands/import_tower_hamlets.py
This chunk is enough for one PR.
* Boston is the substantial change - it now handles stations serving multiple districts correctly.
* South Cambridgeshire is another ropey one like Pembrokeshire. There are less polling stations than districts but no IDs to link them, so we'll end up providing less than 100% coverage, but it is as good as it can be given the data provided.
* Tower Hamlets, Islington, Lambeth, Salford and Reading are efficiency/formatting improvements only.
Refs #216
=> Issue 216 fixes - part 2

polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_camden.py
Given the number of formats Camden publish, I thought this would be easy, but I couldn't get their KMZ output to parse in GEOS. The KML would parse, but the metadata was stored in `ExtendedData` tags with no schema definition in the head, so GEOS wouldn't parse anything other than the boundaries.. In the end, I went for their 'JSON with WKT strings embedded in it' (if only some kind of specialised JSON-based format for geographic data existed!) and XML outputs. Maybe it would have been quicker to just download the SHP and CSV files, but hopefully the `BaseGenericApiImporter` class will be useful in the future and this will be easier to update when they publish new data.
The meta-data says this is the polling data for "GLA Mayoral and Assembly Elections - Thursday 5 May 2016" so it is …
=> Import script for Camden

polling_stations/apps/data_collection/data_quality_report.py, polling_stations/apps/data_collection/management/commands/data_quality_report.py
I decided to formalise a bunch of the checks I've been doing on imported data into a report we can run to flag up possible problems with data or import scripts and make it easier to debug import scripts when writing them. Using this code, we can run something like:
`python manage.py data_quality_report S12000036`
to spit out a data quality report for Edinburgh.
Note that the warnings aren't necessarily errors - in some cases, they just flag limitations of the data. For example, if we run
`python manage.py data_quality_report E09000009`
it will tell us there are 5 invalid district references. This isn't a problem we can fix - as I've noted in PR #221 this is just what the data says, but it is useful to be able to find this stuff out with one command rather than lots of tedious manual …
=> Data Quality Report

polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_finder/fixtures/test_routing.json, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/pollingstations/migrations/0006_residentialaddress_slug.py, polling_stations/apps/pollingstations/models.py, polling_stations/urls.py
Because slug is `UNIQUE` and `NOT NULL`, you won't be able to apply the migration with data already in the DB, so you'll need to clear the ResidentialAddress table, apply the migration and re-run `import_denbighshire` and `import_rct`.
Closes #194
=> Use slugs instead of ids for /address endpoint

polling_stations/apps/data_collection/data_quality_report.py, polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/data_quality_report.py, polling_stations/apps/data_collection/migrations/0005_dataquality_report.py, polling_stations/apps/data_collection/migrations/0006_auto_20160415_1858.py, polling_stations/apps/data_collection/migrations/0007_auto_20160415_1931.py, polling_stations/apps/data_collection/models.py, polling_stations/apps/data_collection/urls.py, polling_stations/apps/data_collection/views.py, polling_stations/apps/pollingstations/migrations/0007_dataqualityreport.py, polling_stations/apps/pollingstations/migrations/0008_auto_20160415_1854.py, polling_stations/apps/pollingstations/models.py, polling_stations/templates/data_collection/dataquality_detail.html, polling_stations/templates/data_collection/dataquality_list.html
Following on from our conversation in the standup on Tuesday, I've added the data quality report output to the website. At the moment, it is just chucking the same output we send to the console into a text field and rendering it in a `<pre>` tag, but it does the job - we can always tidy up later. Thinking it through, the league table is actually the sensible place for this to be linked so I've made some improvements to that as well.
I've marked this WIP because we probably don't want to merge this (or at least shouldn't deploy it to live) until we tear down and re-run the import scripts because the import scripts will populate the `DataQuality` model with suitable static/cached values.
Closes #237
=> Publish data quality reports on website

polling_stations/api.py, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/pollingstations/migrations/0009_customfinder.py, polling_stations/apps/pollingstations/models.py, polling_stations/templates/postcode_view.html
I've generalised this feature a bit so that as well as covering custom polling station finders (Issues #179, #174, GLA tool), it can also be used to show a custom message (e.g: "coming soon") as requested in #199.
Notes on this:
Seed data
----
I haven't provided any seed data for this - just some rough examples of how you might populate the DB in this comment: https://github.com/chris48s/UK-Polling-Stations/blob/152f0ca8e1cac16cfd15986b51bbd883ab4713b7/polling_stations/apps/pollingstations/models.py#L135
I'll leave the finer points of which areas you want to include and how you want to word the copy to you. When you decide what you're putting in there, could you let me know/commit a migration/send me a SQL dump or something so I can mirror the same content in my dev db.
Translations
---- …
=> Add ability to serve custom content for specific areas

polling_stations/apps/data_finder/views.py, polling_stations/settings/base.py, polling_stations/templates/postcode_view.html
Add ability to switch to between tile layers easily
This PR adds the ability to control which tile layer is used by setting environment variables. It should merge cleanly with PR #253.
Options are:
* To use the MapQuest Open tile layer, either do nothing (this is the default behaviour) or set env var `TILE_LAYER='MapQuestOpen'`
* To use the OpenStreetMap tile layer, set env var `TILE_LAYER='OpenStreetMap'`
* To use the MapQuest developer API, [sign up for an free API key](https://developer.mapquest.com/plan_purchase/steps/business_edition/business_edition_free/register) and set env vars `TILE_LAYER='MapQuestSDK'` and `MQ_KEY='your api key'`
* The MapQuestOpen tile layer is limited to 15,000 transactions per month. If/when we hit that limit, it will just stop working - we won't get a …
=> Add ability to switch to between tile layers easily

polling_stations/templates/campaign_signup.html
Changed 'this' for 'find their polling station'. 
Removed the bit about full mailing list.
=> Copy clean-up for polling stations campaign sign-up

polling_stations/api.py, polling_stations/apps/data_collection/constants.py, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/views.py, polling_stations/templates/postcode_view.html
* We can now set environment vars `MAPIT_URL` and `MAPIT_UA` to specify a custom url and user agent for calls to mapit. If not set, the default is http://mapit.mysociety.org/ and blank user agent.
* If using MySociety's mapit install and we hit their rate limit, show a slightly more user-friendly error message.
=> Use custom mapit install with env vars, handle hitting rate limit

polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_southwark.py
This is based against `addressbase_postcode_fixes` (#308), so merging is blocked on that.
Fixes #320
=> Import Southwark

polling_stations/templates/postcode_view.html
WCIVF isn’t relevant for the EU ref, and shouldn’t be mentioned.
=> Remove link to WhoCanIVoteFor in sidebar

polling_stations/settings/base.py
Should fix #345 in prod if you haven't manually set an env var `TILE_LAYER`
=> Change default tile layer to OSM

polling_stations/apps/data_collection/constants.py, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-without-address-picker/then-i-submit-the-only-form.yaml
Anonymous usage of Mysociety's Mapit is now rate-limited to 10 calls per minute: http://mapit.mysociety.org/account/signup/
I've proposed switching the default to DC's mapit as this is what I'm using in dev at the moment. Possibly we want to add the ability to specify a mapit key? Can discuss when we catch up..
Just to give you a quick update on the bigger picture, I know I've been quiet for a bit, but I've got some major changes to the base import classes in progress - just not ready for a PR yet. I am on the case though :)
=> Change default MAPIT_URL to http://mapit.democracyclub.org.uk/

polling_stations/apps/data_collection/data_quality_report.py
As noted in comments around PR #359, we only need to define these in the constructor.
=> only declare object properties in data quality report classes

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/filehelpers.py, polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_city_of_london.py, polling_stations/apps/data_collection/management/commands/import_ealing.py, polling_stations/apps/data_collection/management/commands/import_guildford.py, polling_stations/apps/data_collection/management/commands/import_salford.py, polling_stations/settings/base.py
As discussed in issue #356, I've found a bunch of APIs/open data portals serving up data on polling stations and districts. To try and find out how up-to-date/stale this data is, I've written a bunch of [scrapers](https://morph.io/wdiv-scrapers) that run every day, poll the apis to detect changes and also pull the data into morph because:
* It allows us to do a bit of pre-processing/getting the data into a more consistent format
* Yay - open data for everyone!
This PR adds an base class for importing this scraped data from morph.
In order to download data from morph, you need an API key. If you sign in to morph with GitHub it will give you a key for your github account and any orgs your are a part of. You can use your own, or the DC org's key, but I don't think it really makes any …
=> Add BaseMorphApiImporter class

polling_stations/templates/address_select.html
This fixes issue #189 for Chrome on Android.
I used http://www.browsershots.net/ to generate some screenshots on various versions of Safari on iOS and it appears that this isn't an issue for iPhones because Safari on iOS displays this element in the same way as a desktop browser. It would be useful if someone with an actual iJobbie of some description could confirm that.
The reason I've added the css conditionally using javascript like this is you don't want to set `'-webkit-appearance:menulist;'` because this makes it look odd when webkit-based desktop browsers display the full-height version.
=> Make address_select view clearer on Android

.gitignore, polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/s3wrapper.py, polling_stations/settings/base.py, requirements/base.txt
Putting this here so you can see where I've got to with it but not ready to merge yet.
For the moment, I've added the ability to grab data from S3 alongside the existing options for importing from data in the repo or a local private dir without 'disturbing' that logic too much. However this is still WIP - there's a few things I'd like to dicuss before finalising/tidying up so not ready to merge yet.
Rough topics are:
- Should we take this opportunity to re-organise the structure of the data, or just replicate the existing structure?
- How do we enable people other than use (i.e: who don't have an account on the DC S3 bucket) to write import scripts?
- Do we want to retain the ability to import data held locally?
- How much do we need to retain backwards compatibility for old import …
=> Add ability to import data from amazon S3

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/geo_utils.py, polling_stations/apps/data_collection/management/commands/import_camden.py, polling_stations/apps/data_collection/management/commands/import_daventry.py, polling_stations/apps/data_collection/management/commands/import_mid_sussex.py, polling_stations/apps/data_collection/management/commands/import_york.py
* Factor out `convert_linestring_to_multiploygon()` to a common library where it can be shared by multiple import scripts (there may be some other things we need to factor out into `geo_utils.py` at some point).
* Add `pre_import()` hook method so we can perform setup tasks without overriding `import_data()` in import scripts
* Add import script for Daventry
=> Import script for Daventry + some tidying

polling_stations/apps/data_collection/s3wrapper.py
Looks like the s3 client Joe is using denotes a key is a directory by ending with a trailing slash, rather than `$folder$` like s3fox does.
=> Ensure directory keys are ignored in s3wrapper

polling_stations/apps/data_collection/management/commands/import_pembrokeshire.py, polling_stations/apps/data_collection/s3wrapper.py
Based off PR #405
Closes issue #398
The data supplied by Pembrokeshire doesn't include points or postcodes. The districts shapefile just has a 'station address' column. This means we can't show maps/directions - only an address. Sometimes this is reasonably good (e.g: "Albany Church Hall, Hill Street, Haverfordwest"). Sometimes it is a bit vague (e.g: "Pembroke Rugby Club").
When I first started doing this, I was fairly gung-ho about trying to do stuff like attach missing points and postcodes to addresses by geocoding. However more recently, I'm tending towards the approach of just publishing the data we're given as my impression is that it is more advantageous to be telling councils we aren't fiddling about with their data.. so I haven't tried to do anything clever with it.
=> Import script for Pembrokeshire

requirements/base.txt
I've been seeing build errors in Travis on my fork, but the tests were passing locally and the Travis build on this repo for the same commits are passing. See:
https://travis-ci.org/chris48s/UK-Polling-Stations/builds/189648477
https://travis-ci.org/DemocracyClub/UK-Polling-Stations/builds/189650389
(same commit)
https://travis-ci.org/chris48s/UK-Polling-Stations/builds/189815624
https://travis-ci.org/DemocracyClub/UK-Polling-Stations/builds/189817109
(same commit)
After some hours of pulling my hair out, I tracked down the issue:
* A new version of `libsass-python` (0.12.2) was released on Jan 5th
* The travis build on my fork is fetching this latest version (0.12.2), whereas the travis build on the DC upstream is still using a cached copy of 0.12.1, which is why the build errors aren't …
=> pin libsass to >=0.12.3

polling_stations/apps/data_collection/management/commands/import_lichfield.py
When running this import, you'll note that there are several stations which aren't attached to any district. I think the reason for this is that for constituency-based elections, Lichfield is covered by 2 constituencies - one of which also covers part of a neighbouring local auth. My guess is that Lichfield electoral services organise the polling stations for that whole constituency and have included all of the stations they administer in their file:
so I think it is legit that some of the stations in the file just don't have a corresponding district.
Additionally there is one orphan district which I've asked Joe to follow up with them. Will update if we get a response.
=> Import script for Lichfield

polling_stations/settings/constants/councils.py
Re-importing councils on prod with this change will close #386 but bear in mind caveat about issues with Northern Ireland councils on the DC mapit.
=> make councils import script harvest Isles of Scilly

polling_stations/apps/data_finder/helpers.py
If we try to feed something into mapit that doesn't match a route, the 404 mapit response is html not json (because it is Django's router throwing the 404 - none of the view code is ever invoked in this situation). Trying to parse it as json throws `ValueError`. This patch fixes that by re-throwing it as `PostcodeError`.
This also sort of addresses issue #372, in that if this happens as a result of requesting something like `/postcode/tel:029`, the user now sees
```
Sorry, we can't find tel:029
This doesn't appear to be a valid postcode.
```
instead of throwing an unhandled exception.
Looking at the info in Sentry ( https://sentry.io/democracy-club-gp/pollingstationsprod/issues/168417308/ ), 93% of these errors are from IE6 on Windows XP (I guess because IE6 just doesn't understand what …
=> Correctly handle mapit 404

requirements/base.txt
In general we aren't very good about keeping dependencies up-to-date, but we should try and be better at it. Django seems like a good place to start.
This is the most recent 1.8.x (LTS) release of django and contains various bugfixes and patches for security vulns. All the tests pass and I've been running this version of django on my dev copy for a few days while working on stuff and I've not noticed any issues.
=> Upgrade django to 1.8.17

polling_stations/apps/pollingstations/migrations/0012_auto_20170211_1443.py
If I run `python manage.py makemigrations`, it spits out this. Most of it is just bits where we've added `help_text` to fields but there's also an index that doesn't seem to have been applied. Lets get the DB in sync with the models..
=> add missing migration

polling_stations/apps/data_collection/urls.py, polling_stations/apps/data_collection/views.py, polling_stations/templates/data_collection/morph_report.html
Had this knocking about for a while now. There may be one or 2 kinks still to work out with scrapers that occasionally generate a false positive (i.e: reporting the data has changed when the content isn't fundamentally different) but I think at this stage it is probably useful to get it in the repo. It will provide useful info about which import scripts we need to re-run as we get closer to the elections in May.
=> Scraper report

polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_address_sorter.py, polling_stations/apps/data_finder/views.py
Had a look at whether we should split address into multiple fields in the `ResidentialAddress` table, but I've come to the conclusion we will just end up solving this same problem many times over in import scripts.
This change fixes the problem identified in issue #440 and adds some tests to formalise the behaviour of the new class `AddressSorter`. If we find any more edge cases, we should fix and add additional test cases to `test_address_sorter.py `.
Closes #440
=> Improve address sorting

polling_stations/apps/data_collection/management/commands/import_ribble.py
Another un-parsable shp file here. Was getting errors like `OSError: [Errno 22] Invalid argument` and `struct.error: unpack requires a bytes object of length 8` from GEOS. Couldn't fix it so I did the same 'read it into QGIS and export as GeoJson' trick I used on Hart to get something importable. Again it is `urn:ogc:def:crs:EPSG::27700`.
We've got one orphan district so I've asked Joe to follow it up. If they get back to us with a correction, I'll update.
Closes #507
=> Import script for Ribble Valley

polling_stations/apps/data_collection/base_importers.py
In situations where we have (for some reason) manually returned a district geometry in a shp/geojson importer, the key will be called `'area'` not `'location'`. This is not something we often do (I think this is only here if we need to fix a corrupt polygon or something) so I never spotted it.
=> Bugfix for import_polling_districts

polling_stations/apps/data_collection/management/commands/import_hart.py
I don't think there is anything actionable to do based on this, but I want to explain what I've done just so that someone else is aware of it.
* Districts shapefile supplied by Hart was corrupt in 2 ways:
* It was misreporting its CRS as WGS84, but the co-ordinates were actually in UK National Grid.
* There was a feature with a null geometry (with a district code that doesn't appear in the stations file).
* I was able to import the file into QGIS (if I manually set the CRS correctly), but GDAL was only able to parse up to the null geometry. It wouldn't import anything else in the file after that.
* I tried fixing the shapefile by re-exporting the layer from QGIS - same problem
* I tried fixing the shapefile by running `ogr2ogr -skipfailures fixed_shapefile.shp corrupted_shapefile.shp` - …
=> Import script for Hart

.coveragerc
=> ignore files called tests.py in coverage reports

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/filehelpers.py, polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_lichfield.py
This PR adds the ability to import zipped files straight from the web (instead of downloading and uploading to S3, which is what we do at the moment). I originally did this work in the context of Uttlesford and wrote the base classes before realising that their data had major problems. I've decided to pull the work on the base classes out and merge it ahead of that as we haven't had any response from them.
At the moment, this just makes it easier to update data from Lichfield if they publish new data. This is a useful improvement in itself, but I've also added `BaseApiCsvStationsShpZipDistrictsImporter`. Right now no importers use this but if we get updated data from Uttlesford, this will be the class to use. These classes may also prove useful for importing data from other councils.
=> Add ability to import zipped shapefile/csv from the web, update Lichfield importer

polling_stations/apps/data_collection/management/commands/import_eden.py, polling_stations/apps/data_collection/management/commands/import_leeds.py
Looks like we moved a class and didn't update the `import` statements.
Not tested as morph is [currently down](https://github.com/openaustralia/morph/issues/1129) but they will at least load now.
=> fix Leeds and Eden import scripts

polling_stations/templates/base.html, polling_stations/templates/base_embed.html, polling_stations/templates/postcode_view.html, polling_stations/templates/privacy.html
Open external links in new tab
I've done this in response to issue #342 where it is particularly important because it is really annoying if external links open inside an iframe.
That said, I think the correct behaviour should be that regardless of embedded/non-embedded, links to external sites (google maps, electoral commission, facebook, etc) should open in a new tab anyway (as we're already doing with the "Read more about voting in the UK" link). However, this is not a completely clear-cut issue - not everyone has the same preference.
Reckons?
=> open external links in new tab

polling_stations/apps/data_finder/helpers.py
Turns out Mapit will sometimes return a `200 OK` but no point or areas. e.g:
http://mapit.democracyclub.org.uk/postcode/JE37DW.html
http://mapit.democracyclub.org.uk/postcode/JE37DW.json
(this particular postcode is in Jersey).
These postcodes were causing us to throw an unhandled exception. This patch converts this to a `PostcodeException` which we handle cleanly.
Closes #573
=> Throw PostcodeError on 'No location information' from mapit

polling_stations/apps/data_finder/views.py
See comments in issue #608 for more detail. The following calls all do something sensible:
`/postcode/?postcode=CV3%202DF`
`/postcode/?postcode=CV3+2DF`
`/postcode/?postcode=cv32df`
`/postcode/?postcode=CV6%207JF`
`/postcode/?postcode=CV6+7JF`
`/postcode/?postcode=cv67jf`
`/postcode/?postcode=blablabla`
`/postcode/?postcode=`
`/postcode/CV3%202DF`
`/postcode/cv32df`
`/postcode/CV6%207JF`
`/postcode/cv67jf`
`/postcode/blablabla`
`/postcode/`
Coventry have actually added some javascript to their form which converts everything to uppercase and strips the whitespace, but we should have this in place on our side in case people don't have JS enabled or other councils would like to do something similar.
closes #608
=> Improve validation on postcode endpoint

polling_stations/apps/pollingstations/migrations/0013_customfinders.py
I'm not 100% sure this is the best way of doing this in the long term:
Good: CustomFinders are automatically added when migrations are run,
meaning we don't need to figure out a new system for importing them.
They are also checked in to version control, meaning we should have a
good idea of what's active on any deploy.
Bad: After some time we might add and remove lots of custom finders
meaning that we have loads of migrations adding and removing them
over the history of the app. This will slow everything down and
generally not be useful.
I'm going to stick with this for the time being though, as for the moment
we only have 2, and the EONI one is likely to be there for a long time.
=> Add CustomFinders in data migrations

polling_stations/apps/data_collection/management/commands/import_daventry.py
Closes #535
I haven't bothered to generalise this out as there are a few bits where I'm not sure if the behaviour I'm seeing is down to FastKML's implementation or just the way this particular data is formatted. I'll generalise it out into a base class if/when we encounter more data matching this pattern.
Given the issue described [here](https://github.com/chris48s/UK-Polling-Stations/blob/daventry20170408/polling_stations/apps/data_collection/management/commands/import_daventry.py#L31-L46), it is probably worth running this one before doing the next deploy _just to be sure_. Daventry's mapping server seems to be a little on the tempremental side!
=> Fix Daventry import script

polling_stations/apps/data_finder/views.py
this will stop the `MultiValueDictKeyError` emails
=> fail cleanly if post data doesn't contain 'postcode'

polling_stations/apps/pollingstations/models.py, polling_stations/apps/pollingstations/tests/test_polling_station_manager.py
Was looking at something else and realised this is still here. I think we left this case here to deal with City of London lat year, but it may now be returning an incorrect result in situtations where we have an orphan district, which does occasionally happen. If we can't attach a station to a district using `polling_station.polling_district_id` or `polling_district.polling_station_id`, this function should return `None`. We hold no data this year that should be matching this case.
=> Never fall back to station in district lookup

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/management/commands/import.py
This isn't the most sophisticated approach to this, but I've added a flag which allows us to set particular import scripts not to run in parallel (even when we run with the `--multiprocessing` argument). I've then used that to set all the Scotland scripts to run in series.
Closes #720
=> Fix race conditions running Scotland import scripts

polling_stations/apps/api/postcode.py, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_address_sorter.py, polling_stations/apps/data_finder/views.py
Deploying this will sort out the address picker on the EC's YourVoteMatters site and also help us out when we come to implement the address picker on WCIVF as we don't really want to have to implement this same logic across multiple sites.
Closes #744
=> Sort addresses in API outputs

polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_ee_wrapper.py, polling_stations/templates/election_explainers.html
Use the actual election title from EE for the explainer title instead of embedding a generic title in the markdown.
This needs a bit of faffing to co-ordinate deploying changes across EE, WhereDIV and WhoCIVF. Synchronise watches :watch:
=> use election titles from EE

polling_stations/settings/base.py
In some cases we might want to define `INSTALLED_APPS` which are only relevant in a production setting. Specifically I'm thinking about `raven` right now so we can fix https://github.com/DemocracyClub/polling_deploy/issues/26 but in principle there might be others..
=> allow local.py to define further installed apps

polling_stations/apps/data_collection/management/commands/misc_fixes.py
Central Library is not a station for `parl.2017-06-08`
=> remove custom point for Manchester Central Library

polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/views.py
In a lot of the facebook traffic hitting WhoCIVF from facebook the postcode is in the form `AA1+1AA` (i.e: with the space encoded as a `+`). At the moment this will just fail on WhereDIV because the plus character is not stripped.
This commit qucikly papers over that crack.
Refs #678 but does not fix
=> strip non-alphanumeric chars from spaces in more places

polling_stations/apps/data_collection/ems_importers.py, polling_stations/apps/data_collection/management/commands/import_hounslow.py, polling_stations/apps/data_collection/management/commands/import_south_ribble.py, polling_stations/apps/data_collection/management/commands/import_sutton.py
Worryingly, after recieving a report from a council we discovered that in their data the same `pollingstationnumber` could describe more than one place.
station number 53 was both
Victoria Park Comm Centre and
Highbridge Community Hall
and station number 56 was both
Axbridge Town Hall and
Woolavington Village Hall
This commit switches Halarose importers so that the default behaviour is to use `pollingstationnumber` and a slug of the station name as the id
Also some updates to special-case Halarose importers to account for the change
=> Don't assume that pollingstationumber is unique in Halarose base class

polling_stations/apps/data_finder/views.py
I removed the API call to EE for fear of it becoming a performance bottleneck.
Now that there aren't elections happening, this probably does serve a useful function so lets put it back..
More generally we probably want to work out how to scale this properly
=> Revert "Remove calls to EveryElection"

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/management/commands/import.py
One of the things we have talked about is adding additional automated checks to the import process to reduce the overhead of manually checking data and detect certain avoidable errors more easily.
There are more of these to add, but the first one I've picked is logging a `WARNING` if a polling station is located outside the target council area. This is not always an error - sometimes this is valid, but it is worth flagging for follow up if it happens.
As I add more of these checks, each one is going to add additional overhead to the execution of an import script and cumulatively this will slow down image builds. To counteract this, I've set it up so the checks are on by default if we're running a single script but off by default if we're running scripts in bulk using `import.py`. See the …
=> warn if station point is outside target local auth

polling_stations/apps/data_finder/directions_clients.py, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_directions_helper.py, polling_stations/apps/data_finder/tests/test_google_directions.py, polling_stations/apps/data_finder/tests/test_mapzen_directions.py, polling_stations/assets/js/polyline/.eslintrc, polling_stations/assets/js/polyline/.gitignore, polling_stations/assets/js/polyline/.travis.yml, polling_stations/assets/js/polyline/API.md, polling_stations/assets/js/polyline/CHANGELOG.md, polling_stations/assets/js/polyline/LICENSE, polling_stations/assets/js/polyline/Makefile, polling_stations/assets/js/polyline/README.md, polling_stations/assets/js/polyline/bin/polyline.bin.js, polling_stations/assets/js/polyline/index.js, polling_stations/assets/js/polyline/package.json, polling_stations/assets/js/polyline/src/polyline.js, polling_stations/assets/js/polyline/test/polyline.test.js, polling_stations/settings/constants/directions.py, polling_stations/settings/testing.py, polling_stations/templates/postcode_view.html
It feels like quite a long time since I've written one of my pull request novels :) So what's goin on here then...
We have several directions-related problems that need solving:
* Our approach to directions just draws lines connecting points - we want curvy lines
* Google maps won't let us buy more than 100,000 requests per day
* The Open Route Service fallback code was broken so we had no fallback provider
To that end I have:
* Removed the broken Open Route Service code
* Modified the google maps code to use the `overview_polyline` (so we get smoothed shapes if we're using google maps)
* Added a directions client for [mapzen](https://mapzen.com/) (according to [mapzen's pricing](https://mapzen.com/pricing/#turn-by-turn) we should be able to buy as many requests as we need but it is worth …
=> [WIP] improve directions

.travis.yml, polling_stations/apps/data_finder/features/index.py, polling_stations/settings/testing.py
After lots of testing and debugging, I've worked out we are hitting this: https://github.com/travis-ci/travis-ci/issues/3251
Not sure exactly why we're hitting it more frequently now - maybe something we've changed, maybe something in the travis environment (e.g: recent upgrade to trusty builds). Either way, it has become frequent and annoying.
I've tried various things to try and fix this - older version of `phantomjs`, newer version of `phantomjs` (some people seem to have had better/worse luck with different versions, various bits of discussion buried in https://github.com/travis-ci/travis-ci/issues/3225), tweaks to the webdriver config and so on. None of it works..
I've seen some people who have managed to work around the problem using some variation of "if it throws a …
=> make flaky tests less flaky

polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_addressbase_geocoder_adapter.py, polling_stations/apps/uk_geo_utils/fixtures/addressbase_geocoder/AA11AA.json, polling_stations/apps/uk_geo_utils/fixtures/addressbase_geocoder/BB11BB.json, polling_stations/apps/uk_geo_utils/fixtures/addressbase_geocoder/CC11CC.json, polling_stations/apps/uk_geo_utils/geocoders.py, polling_stations/apps/uk_geo_utils/models.py, polling_stations/apps/uk_geo_utils/tests/test_addressbase_geocoder.py
* Move `AddressBaseGeocoder` to `uk_geo_utils` app
* Generalise `AddressBaseGeocoder` a bit:
* Various changes to support working with UPRNs in anticipation of being able to query by UPRN as well as postcode (coming soon)
* Throw a few new exception types (`NorthernIrelandException`, `AddressBaseNotImportedException`) in anticipation of the `uk_geo_utils` library being used in EE/WhereDIV Northn Ireland is in-scope or where we may only going to want to import the ONSPD and easily fall back to it (coming in [part 4](https://github.com/DemocracyClub/UK-Polling-Stations/pull/1070) ).
* Replace `data_finder.helpers.AddressBaseGeocoder` with a `AddressBaseGeocoderAdapter` layer. Ultimately as part of this larger project, I think I'm going to modify the calling code to talk directly to …
=> uk_geo_utils app part 3

polling_stations/apps/data_collection/google_geocoding_api_wrapper.py, polling_stations/apps/data_finder/checks.py, polling_stations/settings/base.py, polling_stations/settings/constants/councils.py, polling_stations/settings/constants/mapit.py
Once PRs #1070 and #1071 are merged, all of the code that interacts with mapit will be removed. Once those are done, this PR finishes the cleanup and removes the last few references and settings. When those PRs are reviewed/merged I can rebase this changes on to `master` and then the tests should pass. Obvs the build is currently broken as there is still code under test on this branch which is expecting these settings to exist.
=> Remove last few mapit references

polling_stations/apps/data_collection/views.py
fixes `FieldDoesNotExist: Council has no field named 'location'`
=> fix league table view

polling_stations/apps/data_finder/features/index.py, polling_stations/apps/data_finder/features/smoke_tests.feature
See commit messages, but basically I've added some more fairly cursory smoke tests just to get more code running under test (reasons for this to become more obvious). Adding a bunch more integration tests has amplified the problems with intermittent build failures, so I've also added a workaround to retry the `selenium.common.exceptions.TimeoutException` s. As noted in PR #1064 this isn't my preferred solution, but there doesn't really seem to be a clean way around it :(
=> Add more end-to-end tests, make travis build less flaky (again)

polling_stations/apps/data_finder/features/index.feature, polling_stations/apps/uk_geo_utils/helpers.py, polling_stations/apps/uk_geo_utils/tests/test_postcode_helper.py
92df1e8 seemed like a really good idea... until I realised it was a really bad idea.
Basically, there are a number of places where we are relying on postcode being able to be not-a-postcode. I tried building in cases to handle it, but I just ended up chasing errors further down the stack. I think the best solution is to back out the change but make `validate` an optional constructor param. This will allow us to add in the validation where we want it in a controlled way rather than sledgehammer in loads of places where the app can throw an exception all at once.
Note that although it looks like I'm removing useful validation here, this basically just puts us back where we were before 6339794 but with the postcode functions moved into a class.
Closes #1077
=> back out changes in 92df1e8

README.md, polling_stations/apps/api/address.py, polling_stations/apps/api/postcode.py, polling_stations/apps/api/tests/test_address.py, polling_stations/apps/api/tests/test_postcode.py, polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/ems_importers.py, polling_stations/apps/data_collection/management/commands/import_barnsley.py, polling_stations/apps/data_collection/management/commands/import_bexley.py, polling_stations/apps/data_collection/management/commands/import_bromley.py, polling_stations/apps/data_collection/management/commands/import_calderdale.py, polling_stations/apps/data_collection/management/commands/import_hillingdon.py, polling_stations/apps/data_collection/management/commands/import_rct.py, polling_stations/apps/data_collection/management/commands/import_redbridge.py, polling_stations/apps/data_collection/management/commands/import_richmond.py, polling_stations/apps/data_collection/management/commands/import_torfaen.py, polling_stations/apps/data_collection/management/commands/import_tower_hamlets.py, polling_stations/apps/data_collection/management/commands/import_westminster.py, polling_stations/apps/data_collection/management/commands/import_wycombe.py, polling_stations/apps/data_finder/features/smoke_tests.feature, polling_stations/apps/data_finder/fixtures/test_routing.json, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_addressbase_geocoder_adapter.py, polling_stations/apps/data_finder/tests/test_geocoders.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/pollingstations/models.py, polling_stations/apps/uk_geo_utils/geocoders.py, polling_stations/apps/uk_geo_utils/tests/test_addressbase_geocoder.py, test_data/vcr_cassettes/integration_tests/feature-smoke-tests/scenario-check-example-page/given-i-visit-httplocalhost8081example.yaml
Closes #1087
Closes #1088
This PR is mainly about accounting for the consequences of changes I've made to the geocoders through the rest of the codebase and formalising the decision that we're going to continue with our 'additive' approach to importing data.
To resolve #1087 I have added a `strict` mode in 75edfa0 so that if we're using this library in another application we can use `strict=True` to require that every UPRN in our AddressBase table is matched in the ONSUD before returning a result if we have the option follow up by querying by UPRN. Alternatively we can use `strict=False` in a situation like this where our address data isn't necessarily keyed by UPRN (and if it is those UPRNs aren't necessarily in AddressBase, and so on..)
Most of the rest of it is cleanup to address the …
=> Tidying up and finishing off on geocoders

.coveragerc
This is making the stats go wobbly
=> don't include aloe/selenium code in coverage reports

polling_stations/apps/councils/management/commands/import_councils.py, polling_stations/apps/councils/tests/test_council_importer.py, polling_stations/settings/constants/councils.py
Closes #1081
I hit some issues with the ONS geo portal being a bit flaky today. Not happened before, but if I hit it again I might add a command line param we can use to easily override this URL with a local file or alternative URL (e.g: if we grab a copy and stick it on S3).
=> fetch GB and NI boundaries in one request

polling_stations/apps/api/fields.py, polling_stations/templates/api_docs/blueprints/finder_responses/BN436HW.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/NG178AA.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/SW1A1AA.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/e07000223-527-5-truleigh-way-shoreham-by-sea-west-sussex-bn436hw.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/schema.apibp
Closes #1047
Note this is a backwards-compatibility breaking change so we need to consider impact on consumers:
* It doesn't affect WhoCIVF because we don't use the origin point (only the station point, which *is* a valid GeoJSON feature)
* It doesn't affect the EC - they only use the station address
* We need to update the widget. I'll submit a PR to update https://github.com/DemocracyClub/WhereDoIVote-Widget/blob/9b291eeac792954c8e68add4d60581c454007edd/src/WdivAPI.js#L27-L30 when this is deployed.
* It may affect some of: Labour Party, Best for Britain, Democratic Dashboard. We should probably drop our contacts at those orgs an email in the run-up to May
=> make postcode_location key a valid GeoJSON feature

polling_stations/apps/api/fixtures/test_address_postcode.json, polling_stations/apps/api/postcode.py, polling_stations/apps/api/tests/test_postcode.py
Not the most elegant edge case to handle, but Closes #963
=> make API and front-end behave consistently if we can't geocode

polling_stations/apps/councils/management/commands/import_councils.py, polling_stations/apps/councils/tests/test_council_importer.py
The ONS API seems to be a bit flaky at the moment and sometimes serves up an incomplete file causing the importer to fail with `JSONDecodeError: Expecting ',' delimiter: line 1 column nnnnn`.
This allows us to grab a good copy, put it on S3 and fetch it from there instead. I'm going to merge this straight off as I need it to build an image.
=>  allow alt BOUNDARIES_URL to be specified at runtime 

polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_ee_wrapper.py, polling_stations/settings/testing.py, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-my-address-not-in-list/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-northern-ireland/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-invalid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-valid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-without-address-picker/then-i-submit-the-only-form.yaml
If we've got a (by-)election happening in one ward, querying EE with any postcode in that local auth will return the 'organisation group' election object but there is only an election happening in the specific ward that has a 'ballot' type object.
=> ignore group ids when working out if there is an election

polling_stations/apps/data_finder/views.py
In principle, if we call a url on WhereDIV with a very long string in the UTM tracker vars like
`?utm_source=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
we will throw `value too long for type character varying(100)` trying to log it.
=> truncate really long data in utm tracker params

requirements/base.txt
2.0.0 drops support for Django < 1.10, Adds support for Django 2.0 and drops support for Postgres < 9.4
This dependency can be safely upgraded on the 'client' installs independently of upgrading the main website ( https://github.com/DemocracyClub/Website/pull/102 ) because the API does not change in 2.0.0. All the BC-breaks are just platform compatibility
=> Update dc_signup_form to 2.0.0

polling_stations/apps/addressbase/migrations/0008_auto_20180102_1606.py, polling_stations/apps/addressbase/models.py, polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/contexthelpers.py, polling_stations/apps/data_collection/tests/test_importers.py, polling_stations/apps/data_finder/fixtures/integration_tests_addressbase.json, polling_stations/apps/data_finder/fixtures/test_addressbase.json, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/uk_geo_utils/tests/test_addressbase_geocoder.py, polling_stations/apps/uk_geo_utils/tests/test_import_onsud.py, polling_stations/settings/base.py
Refs #1045
This PR adds the ability to print some contextual information which gives us some idea how many addresses we would expect to find in the input file if it is complete. Because this adds some overhead to the start of the script, I've set it so it doesn't run if we pass the `--nochecks` flags (this means we won't run this code when we do a bulk import to build an image and we can pass it over in unit tests, etc).
I don't really have a good handle yet on which of these numbers is the most useful comparison point or what a sensible warning range is going to be. I think 'Total Dwellings from 2011 Census' is actually going to be the closest number mostly (but a bit on the low side because its fairly out-of-date now) because both of the UPRN totals include non-residential addresses …
=> Show info about expected dwellings in local auth before import 

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/management/commands/import_calderdale.py
Uniquely, Calderdale are now representing their polling stations as a polygon of the building rather than just a point:
Quite cool, but no other council does this, so I'm not particularly keen to handle it beyond reducing it to a point on import. This PR allows us to explicitly handle this case. Note it also chucks out a bunch of warnings because in 99% of cases if the station isn't a point it is more likely to indicate that I'm trying to import the wrong file or something.
=> Deal with stations represented as polygons, import Calderdale

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/tests/test_check_district_overlap.py
Refs #1045
This does several useful things:
1. Report how much of a polling district is inside the target local auth at import time. If its >99%, log an `INFO`, else a `WARNING`. If there is a substantial chunk of a polling district outside the council area this indicates a possible issue. The 1% tolerance gives us a (needed) bit of leeway for "these 2 lines are supposed to be exactly the same but they aren't quite".
2. Performing transformations/calculations on the polygons at this stage has the useful side effect that issues like polygons with implicit SRID or invalid polygons will give us a more explicit warning e.g:
* `ERROR: Calling transform() with no SRID set is not supported`
* `ERROR: Error encountered checking Geometry returned from GEOS C function "GEOSIntersection_r"`
=>  log warning if >=1% of polling district area is outside target local auth

polling_stations/templates/base.html
There are a bunch of notices and attributions we are supposed to have on our site where we use postcode lookups, boundaries, etc (see https://www.ons.gov.uk/methodology/geography/licences ). Lets bung them at the bottom of the footer.
=> add copyright notices

polling_stations/apps/api/address.py, polling_stations/apps/api/postcode.py, polling_stations/apps/api/tests/mocks.py, polling_stations/apps/api/tests/test_address.py, polling_stations/apps/api/tests/test_postcode.py, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_ee_wrapper.py, polling_stations/apps/data_finder/views.py, polling_stations/templates/api_docs/blueprints/finder.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/BN436HW.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/NG178AA.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/SW1A1AA.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/e07000223-527-5-truleigh-way-shoreham-by-sea-west-sussex-bn436hw.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/schema.apibp, polling_stations/templates/fragments/you_dont_need_poll_card.html
Closes #1059
Closes #1128
Definitely don't review/merge this. It is based on assumptions about PRs that haven't been merged and data structures that do not yet exist which may end up not being true. Also needs rebasing onto other stuff to properly finish.
TODO:
* Haven't done the API docs as I'll end up doing it twice to sort out the merge conflict with https://github.com/DemocracyClub/UK-Polling-Stations/pull/1145/commits/ddfa9b52dde25af787a767b168e6c28d7bd44e13 but the format will be roughly that, with an object.
* Write a test for `get_metadata()`
* Once we've got https://github.com/DemocracyClub/EveryElection/pull/223 merged/deployed and started serving up some data I'll finish this off.
In current design we will show something like
but that's in the old theme and we should aim to …
=> voter ID pilot info

polling_stations/templates/fragments/polling_station_known.html, polling_stations/templates/fragments/polling_station_unknown.html, polling_stations/templates/postcode_view.html
Closes #1207
* Move the opening hours on to the same card as the address/map/etc
* Move polling card/voter id info much higher up the page
* Move 'register to vote' card higher up the page (we will remove this card after the deadline on 17th April)
* Move 'information on your candidates' card lower down the page (very few people wanted this or said it was useful)
Although it is useful to look at the diff, it might also be easier to look at screenshots to review this. Rather than pasting lots of large screenshots into a GH issue, I've uploaded them to: https://drive.google.com/drive/folders/1SrJ_CZXJEORrpxwMrvrSxeiOEx28iZkY
There are screenshots for each of the following cases:
* Station not known, without voter ID pilot
* Station known, with map (without voter ID pilot)
* Station known, …
=> re-order results page content

polling_stations/apps/data_finder/helpers.py
No idea how I've never spotted this in the last 2 years!
This was causing unnecessary DB queries because it's basically saying "if we've already run this query run it again".
I think the original intention was that it should be written like this: 170a48d (i.e: "if we _haven't_ already run this query run it")
but we run this query in the constructor, so if the object exists, by definition, we must have run it anyway (unless `@property` implies `@staticmethod` ??), so we can just completely delete this code: 7f29b86 . This saves making multiple unnecessary round trips to the DB on every request. Note that I've deleted this code and all the `RoutingHelper` tests pass.
@symroe - can you just sanity check this.. I've done it as 2 commits just so I can show what I think the original idea was, …
=> Don't make unnecessary DB queries

polling_stations/apps/pollingstations/views.py, polling_stations/settings/base.py, polling_stations/urls.py
This adds a status check endpoint for use with ELB status checking. It checks for a "clean" file (if applicable) and makes sure it can connect to any defined DB connections before returning a `200 OK`. I miiiight look to add some more handy checks to this at some point, but lets ignore that for now.
I've tried deploying this off a branch and it does the job. I'm quite keen to get this deployment work finished off this sprint if possible, so would be handy to get a quick :+1:  on this if you get a chance @symroe
=> add status check endpoint

requirements/base.txt
For some reason Pyup pushed this to a branch but didn't open a PR :confused: 
Its opened a PR on EE today. I'll have to keep an eye on it. If it persists I'll raise a support ticket
=> Update lxml from 4.2.4 to 4.2.5

polling_stations/apps/data_collection/urls.py, polling_stations/apps/data_finder/middleware.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/whitelabel/middleware.py, polling_stations/urls.py
This fixes the following deprecation warnings:
* `RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.`
* `RemovedInDjango20Warning: Specifying a namespace in django.conf.urls.include() without providing an app_name is deprecated. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.`
=> remove some deprecated calls

polling_stations/apps/api/router.py, polling_stations/apps/api/sandbox-responses/AA12AA.json, polling_stations/apps/api/sandbox-responses/AA12AB.json, polling_stations/apps/api/sandbox-responses/AA13AA.json, polling_stations/apps/api/sandbox-responses/e07000223-524-2-truleigh-way-shoreham-by-sea-west-sussex-bn436hw.json, polling_stations/apps/api/sandbox-responses/e07000223-527-5-truleigh-way-shoreham-by-sea-west-sussex-bn436hw.json, polling_stations/apps/api/sandbox.py, polling_stations/apps/councils/tests/test_council_importer.py
I was looking at how to make the behaviour of the widget more demonstrate-able / test-able and decided to basically nick the idea from https://github.com/DemocracyClub/aggregator-api/commit/a53c92e0851907985ca468984a45d434cb3c63e0 and make some 'sandbox', URLs which serve static examples.
This is more difficult to do well here because there is a lot of 'internal linking' between endpoints in this API which is difficult to replicate (so I'm not massively keen to expose this in the docs yet, at least in its current form). What this does allow us to do though is grab a local copy of the widget and set
`REACT_APP_WDIV_API_URL=https://wheredoivote.co.uk/api/beta/sandbox`
in
https://github.com/DemocracyClub/WhereDoIVote-Widget/blob/master/.env.development
Then we've got test postcodes we can …
=> Add sandbox API outputs

polling_stations/apps/api/councils.py
this should fix the random crashes on WDIV when we're deployed on a small instance
Tests will probably fail for unrelated reason and need the fix from 9e17dea
=> exclude area column on councils list route

.travis.yml, tox.ini
- drop testing on python 3.5
- run tests on Postgres 10
=> Update CI build to reflect new live env

polling_stations/apps/api/address.py, polling_stations/apps/api/postcode.py, polling_stations/apps/data_finder/helpers/every_election.py, polling_stations/apps/data_finder/tests/test_ee_wrapper.py, polling_stations/apps/data_finder/views.py
Having thought through https://github.com/DemocracyClub/UK-Polling-Stations/issues/1456 I think the right decisions to take here are:
Data model:
* Special-case voter id pilots and accept that we also need to special-case any other category of spurious election event we add
* In Every Election we must store this stuff at ballot-level not group (by convention). We seem to be standardising on the ballot object as the canonical "unit of election" we expose via our various APIs
WDIV Front-end:
* Assume we won't have >1 pilots with different requirements on the same day at the same polling station :pray:  - if there's one ballot happening with a pilot, just pick one and show that info
WDIV API:
* Continue to present a single top-level `metadata` object aggregating info from all applicable …
=> present a single date-level elections metadata object

polling_stations/apps/data_finder/features/index.feature, polling_stations/apps/data_finder/helpers/directions.py, polling_stations/templates/fragments/polling_station_known.html, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-valid-station-id/then-i-submit-the-only-form.yaml
closes #1271
I've used a crude as-the-crow-flies distance instead of making 2 API calls for performance reasons (and also not rinsing our API key reasons). This is going to be a bit variable depending on how "wiggly" your route is (if you see what I mean), but it should get us into a sensible ballpark and stops us from providing overly ambitious journey suggestions like
> It's about 2.7 miles away or a 53 minute walk from [foo]
Not sure if 1.5km is the _ideal_ threshold (for the most part we're going to stop suggesting walking around the ~half hour walk mark) but this is better than it was before and we've at least now got a threshold we can tweak.
=> Suggest appropriate method of transport based on distance

polling_stations/db_routers.py
Closes #1360
This probably causes the inverse problem if we ever try to use Generic FKs on the default DB connection, but that's probably a good incentive to.. not do that :)
=> route contenttypes app to logger db

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/data_types.py, polling_stations/apps/data_collection/tests/test_address_list.py
Sorry - this PR bundles together more changes into 1 PR than is really ideal.
Broad categories of stuff happening here:
Closes #1205
Instead of
- storing data as a set of namedtuples
- converting to a list of dicts
- changing the data
- changing it back to a set of namedtuples
every time we want to change something, just store it as a list of dicts all the way through the process. This should make things a bit more readable as well as improving performance.
Closes #1329
Predictably, this is not completely clear-cut - a UPRN duplicate isn't necessarily a hard error. Sometimes we get multiple addresses with the same UPRN and its not actually a problem (or not one that we care about, at least). An example of this is sometimes we might see 2A High Street and 2B High Street with the same UPRN …
=> Various Changes to residential address imports class

polling_stations/apps/data_collection/data_types.py, polling_stations/apps/data_collection/tests/test_address_list.py, requirements/base.txt
This is mostly explained inline in the code in some fairly verbose comments, but broadly I'm attempting to:
a) Make better assumptions in the case where UPRN and postcode don't match
b) Warn loudly about a subset of cases where we definitely want to do a manual check/follow-up
Closes #1330
=> be smarter if residential UPRN and postcode don't match

polling_stations/apps/data_collection/data_types.py, polling_stations/apps/data_collection/tests/test_address_list.py, requirements/base.txt
This reverts commit 1fbc213cba7f573933085376e3c770994f72f047.
Having spent a bit of time with 2 of us working with this, I've decided to back it out for now. I think there is merit in the approach, but in this exact form, although we're fixing some issues, we're also _introducing_ new errors and doing it in a way that is hard to undo. Needs more thought/testing
=> Revert "be smarter if residential UPRN and postcode don't match"

polling_stations/settings/constants/councils.py
I'm fairly convinced this is the exact same file as `e50a6790161743038d586e1a9494d9ff_1` with different meta-data, but who knows.. lets get on the latest published version
closes #1518
=> update ONS local auths data

polling_stations/apps/addressbase/models.py, polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/data_types.py, polling_stations/apps/data_collection/management/commands/import_ashfield.py, polling_stations/apps/data_collection/management/commands/import_basingstoke.py, polling_stations/apps/data_collection/management/commands/import_derbyshire_dales.py, polling_stations/apps/data_collection/management/commands/import_fylde.py, polling_stations/apps/data_collection/management/commands/import_hartlepool.py, polling_stations/apps/data_collection/management/commands/import_ipswich.py, polling_stations/apps/data_collection/management/commands/import_manchester.py, polling_stations/apps/data_collection/management/commands/import_portsmouth.py, polling_stations/apps/data_collection/management/commands/import_redcar_cleveland.py, polling_stations/apps/data_collection/management/commands/import_south_norfolk.py, polling_stations/apps/data_collection/management/commands/import_spelthorne.py, polling_stations/apps/data_collection/management/commands/import_wokingham.py, polling_stations/apps/data_collection/management/commands/import_wychavon.py, polling_stations/apps/data_collection/tests/test_address_list.py, requirements/base.txt
Closes #1330
Lets see if we can make a slightly better job of this. I _think_ this is an improvement.
**Key changes:**
* Strip commas before fuzzy matching
* Set default match threshold to 100
* Allow match threshold to be configured on each import script instead of set globally
* Allow fuzzy matching to be turned off if needed
* If we can't fuzzy match, delete any (problematic) leftovers
**Review notes:**
* Still doing this as a post-process:
* Input to `address_record_to_dict()` should match CSV
* There are some things we need to know which require iterating the whole thing
* How do we deal with a single-record correction or exclusion?
* `INFO`s vs `WARNING`s
* ~Is `delete_unmatched_postcodes` setting useful/necessary? Would it be better as a `--flag`~
**TODO:**
* ~Test the changes …
=> be smarter if residential UPRN and postcode don't match (part 2)

polling_stations/apps/data_collection/data_types.py
Had a bash with this today while writing import scripts and made a couple of edits..
* `SUGGESTION` is slightly more consistent with the `rec["accept_suggestion"] = True`/`rec["accept_suggestion"] = False` terminology.
* Including the input address in the comment makes it much easier to check the home point is in the right place when reviewing.
=> Add SUGGESTION: line to postcode mismatch warnings

polling_stations/apps/data_collection/base_importers.py
If `PRIVATE_DATA_PATH` is configured locally, use that. Otherwise fetch from S3
@GeoWill - does this seem fair enough to you?
=> remove 'private' setting

polling_stations/templates/api_docs/blueprints/finder.apibp
Closes #1459
@symroe - I wasn't really sure where to put this. I'm making quite a lot of reference to the `/address` and `/postcode` API endpoints and special cases in those outputs, so it seems like from the perspective of a new user it should come _after_ that section of the documentation. i.e: if you're reading the docs start-to-finish, we should explain the `/address` and `/postcode` endpoints first and then get into the special cases of those outputs. That said, its also something that I want people to read if they're using the API this May.
I think the solution is just to directly link to this section heading when I contact existing API users (this is the last task blocking that mailing) or create any new API keys.
=> api doc updates for May 2019

polling_stations/apps/data_finder/helpers/geocoders.py
This fixes the case where a postcode used to be split between (for example) West Somerset and Taunton Deane, but is now entirely contained in Somerset West & Taunton
`geocoder.get_code("lad")` should not raise `MultipleCodesException` in this situation.
Closes  #1625
=> another fix for new local auths

polling_stations/templates/fragments/no_election.html
closes #1541
This gives us some wording to bikeshed. I've attempted to balance the needs of 3 groups here:
* Providing useful information to members of the public
* Councils who do have parish elections happening in areas that don't have district ward elections and want us not to tell their users "you don't have an election"
* Councils who do have parish elections and don't want loads of people phoning them up to ask if they have an election or not.
For now, lets concern ourselves with the 'happy path'. There is also an edge case where there are several councils where we don't hold very good contact info, but I'm hoping to fix that at the start of April when the new councils become "official".
There is also an edge case for users in NI where the relevant thing to contact is EONI not the …
=> change "we don't know of any upcoming elections" wording

polling_stations/apps/data_finder/helpers/every_election.py, polling_stations/apps/data_finder/tests/test_ee_wrapper.py, polling_stations/settings/testing.py
This will allow us to set `NEXT_CHARISMATIC_ELECTION_DATE = "2019-05-02"` in the settings on the deploy repo to temporarily ignore any elections that may or may not be happening on 2019-05-23 until we're ready to shift focus and deal with them.
=> add NEXT_CHARISMATIC_ELECTION_DATE setting

polling_stations/templates/fragments/cancelled_election.html
This allows us to present for example `<h2>Uncontested Election</h2>` if this is a more specific case of cancelled election.
Also, fix the council phone number link on the generic version (oops)
=> improve cancelled elections template

polling_stations/templates/postcode_view.html
Looking at the feedback, there are quite a few comments along the lines of:
> Looking for ward name so I can check list of candidates
> I want to know who is running and info about them.
> Would be nice to have a link to a list of candidates
> I thought it would tell me the names etc of the candidates.
> IT COULD HAVE ADDED WO IS STANDING
Clearly they are scrolling far enough down the page to find the "complain about this" card, but not as far as the "info on your candidates" card. This moves the "info on your candidates" card above the feedback form.
=> move 'info on your candidates' card higher up

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/filehelpers.py, polling_stations/apps/data_collection/management/commands/import_aberdeen.py
Here's an initial bash at updating the `ScotlandSpatialHubImporter` class. It seems to behave as expected with a couple of scripts, I've attached the Aberdeen one as an example - the duplicate stations in district issue is unchanged from 2017.  
It would be good to get feedback on 71fb6f9  - I'm not sure if the `encoding` kwarg that I've added to the `ShpHelper` class is the best way to go as it's not obvious to me where one would set it in an import script. However it may be an expedient hack that gets us through to June.
=> Spatial hub imports

polling_stations/apps/data_collection/management/commands/import_glasgow_city.py
Extracted from #2011 You should be able to push to this branch.
This one has broadly the same problem as Aberdeenshire - stations and districts files disagree for various codes e.g:
District `AN3723`
* districts file says its "Jordanhill Parish Church Hall, Munro Road (28 Woodend Drive), G13 1QT"
* stations file says its "KELVINDALE PRIMARY SCHOOL, 11 DORCHESTER PLACE, G12 0BP"
District `CC0407`
* districts file says its "City Building Depot, 32 Greenholme Street, G44 4DU"
* stations file says its "CATHCART CONGREGATIONAL CHURCH HALL, 15 GARRY STREET, G44 4AY"
I ended up binning this one in 2017 for this reason, but given Glasgow covers mor than half a million population, I reckon its probably worth chucking a few more hours at trying to get coverage on the districts where the 2 files …
=> import script for Glasgow City

polling_stations/apps/data_collection/management/commands/import_aberdeenshire.py, polling_stations/apps/data_collection/management/commands/misc_fixes.py
Extracted from #1996 You should be able to push to this branch.
This is one which includes the station name in both the districts file and the stations file. I had a quick look over this and noticed there is at least one where they disagree.
District `EG1202`
- districts file says its "FINTRAY PUBLIC HALL"
- stations file says its "Axis Centre"
This is an annoying inconsistency because we don't know really which of the 2 contradicting data points to rely on. Can you revisit this one and have a look at whether there are any other cases of this. If its just the one, can we exclude this and say "we don't know" for this district. If its lots of them, lets re-evaluate it.
=> import Aberdeenshire

polling_stations/apps/councils/data/scotland.csv, polling_stations/apps/councils/management/commands/import_councils.py, polling_stations/apps/councils/management/commands/update_scotland.py
This is tech debt we'll need to review post-May, but lets look at it again in the context of the EC's move to numiko. We'll probably have to rewrite the whole councils import then anyway.
refs  #969
Note: when you merge this, call `./manage.py update_scotland` after importing councils in the deploy scripts
=> improve contact info for Scottish councils

polling_stations/apps/data_finder/features/index.feature, polling_stations/apps/data_finder/views.py, polling_stations/templates/fragments/polling_station_unknown.html, polling_stations/templates/fragments/you_dont_need_poll_card.html, polling_stations/templates/home.html, polling_stations/templates/multiple_councils.html
After making this change, I'm not any more convinced it's useful. One to chat about on the call tomorrow.
As I'd done the work of adding a card that only shows up when polls are open, I thought I'd PR it anyway.
4e229eb changes the "we don't know" page a bit – I think it's slightly better wording than before (e.g not using "data"). Not going to care too much if I'm wrong though. Another thing to ~bike shed~ talk about tomorrow.
=> Europarl home page text

.travis.yml, polling_stations/apps/data_collection/management/commands/import_stevenage.py
I assume black's opinions have changed on the syntactic construct in `import_stevenage.py` have changed since a previous version of black.
chromium-browser has also been updated in our CI test dist (xenial), so this brings in a newer version of chromedriver to match.
Once this is in, other PRs will start passing again.
=> Get CI passing again after external changes to test ecosystem

polling_stations/apps/addressbase/tests/test_addressbase.py, polling_stations/apps/data_finder/helpers/routing.py, polling_stations/apps/data_finder/tests/test_routing_helper.py, polling_stations/apps/data_finder/tests/test_views.py, polling_stations/apps/data_finder/views.py
This pulls redirect URL generation into RoutingHelper so that it can optionally preserve utm_* query parameters.
This then obviates the need for `.get_endpoint()`, which has been removed.
Resolves #1368.
=> Preserve particular query parameters across RoutingHelper redirects

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/data_quality_report.py
This makes some of the report generation less verbose and removes district-related stats from reports when there are no districts loaded for a council.
Closes #1524.
=> Conditionally remove districts from report

polling_stations/apps/data_collection/management/commands/import_oadby.py
Postcodes: 'LE2 4RZ', 'LE18 3UT', 'LE18 3US' and 'LE18 3UX' trigger `WARNING: Discarding record: Postcode centroid is outside target local authority` - ignore for now as I think they are for just/un-built houses. Users will be passed to the 'contact your council page'.
=> Import script for Oadby and Wigston (closes #2138)

polling_stations/apps/dashboard/templates/dashboard/postcode.html, polling_stations/apps/dashboard/views.py
This provides an easy comparison to the council-held address, so that one can less explicitly remember to check for a disparity when investigating an oddity.
=> Include AddressBase addresses in dashboard postcode view

polling_stations/apps/data_collection/management/commands/import_craven.py
100050347440 is wrongly geocoded to be in High Bentham, but is actually in Low
Bentham and has the right postcode, so is fine to leave as is.
=> Import Craven (closes #2423)

polling_stations/apps/data_collection/management/commands/import_rugby.py
No data for properties in the bottom two wards (overlap with Kenilworth and Southam constituency). Raised on Trello.
Previous corrections validated for carrying over, but no more checking has been done on this.
=> Import Rugby (closes #2460)

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/ems_importers.py, polling_stations/apps/data_collection/management/commands/import.py
We generally don't want this behavior in production because it introduced more
problems than it solved - "The church is at the other end of the street!" etc.
However when checking that polling districts and their stations look plausible
it is really useful. So add the flag:
$ manage.py import_place -p
and the postcode centroids will be used to create station points.
I haven't added tests because as far as I can tell the other flags aren't. Can do if it would be valuable.
=> Add use postcode centroids flag

.gitignore
if we clear `/static`, we lose the local `.gitignore`
=> ignore static in base .gitignore

polling_stations/apps/addressbase/helpers.py, polling_stations/apps/addressbase/management/commands/create_blacklist.py, polling_stations/apps/addressbase/models.py, polling_stations/apps/data_collection/data_types.py, polling_stations/apps/data_finder/helpers/geocoders.py, polling_stations/settings/constants/councils.py
Now that we're using the latest ONSPD and we've got rid of ONSUD completely, everything we rely on is using the new codes/boundaries for all these areas.
Refs #1630
Refs https://trello.com/c/4JIFou7P
Refs https://trello.com/c/piIbUuL2
Refs https://trello.com/c/OCFJAUBn
I'm leaving any code in place that uses `OLD_TO_NEW_MAP` and `NEW_COUNCILS` which refs the councils table or ONSPD as we may need this feature again for Buckinghamshire in May 2020 and Northamptonshire in 2021.
I'm removing any code which assumes that the ONSUD exists or could not be up-to-date on the basis that we'll apply modifications to the councils table then generate a uprntocouncil table which reflects those changes, so it will always be as up-to-date as the councils table.
=> remove local auth workarounds

polling_stations/apps/pollingstations/filters.py, polling_stations/settings/base.py
I always forget about this until we're trying to deploy an image, but whenever we do this, we get spammed with a bunch of emails saying `[Django] ERROR (internal IP): Service Unavailable: /status_check/` while the server initializes.
I've never worked out why sentry doesn't swallow this particular error, but its annoying.
This filter should drop this specific log event but pass all others.
=> don't email us about 503 from status_check

polling_stations/apps/data_collection/data_types.py, requirements/base.txt, tox.ini
FuzzyWuzzy is GPLv2 licensed which would force you to licence the whole project under GPLv2. I had the same problem on one of my projects and so I wrote [rapidfuzz](https://github.com/rhasspy/rapidfuzz) which is implementing the same algorithm but is based on a version of fuzzywuzzy that was MIT Licensed and is therefor MIT Licensed aswell, so it can be used in here without forcing a License change. As a nice bonus it is fully implemented in C++ and comes with a few Algorithmic improvements making it between 5 and 100 times faster than FuzzyWuzzy.
=> use rapidfuzz instead of fuzzywuzzy

polling_stations/apps/councils/management/commands/import_councils.py, polling_stations/apps/councils/tests/test_council_importer.py
This is useful for running as an ad-hoc command when a single council
contact detail changes, but also paves the way for consuming contact
details from a 3rd party API on a cron job.
=> Add option to update council contact details

polling_stations/apps/data_importers/tests/test_district_set.py
This commit:
- makes sure all data is torn down after each test.
- Makes it clear that the `update_uprn_to_council` method isn't doing
any spatial lookups when a polling_station_lookup is provided.
=> Improve DistrictSet tests

polling_stations/apps/data_importers/base_importers.py, polling_stations/apps/data_importers/tests/test_base_stations_importer.py, requirements/base.txt
It's not uncommon to find two polling stations with the same lat/lon in
the council file, but different addresses - i.e. one has the wrong
lat/lon. However it's also common to have multiple stations at the same
location, e.g. different rooms in a school. In order to catch the
stations that have been given the wrong location in error, this check
compares the distance between the station to be added to the stationset
and all the stations added so far.
This check won't happen when the --nochecks flag is passed.
This commit also refactors the check_station_point method now there are
two checks, both of which require a location.
The qgis filter expression line allows the user to quickly identify the
stations in question by applying a filter to the polling stations layer.
=> Warn on stations with same location, different postcode

polling_stations/apps/data_importers/management/commands/import_adur.py, polling_stations/apps/data_importers/management/commands/import_dacorum.py, polling_stations/apps/data_importers/management/commands/import_fareham.py, polling_stations/apps/data_importers/management/commands/import_worthing.py
https://github.com/DemocracyClub/UK-Polling-Stations/pull/3048
Added a check for postcodes that are split in council data but won't be
in our data after import. The easiest fix is to not assign any postcodes
to those addresses.
=> Tidy ups to catch split postcodes

polling_stations/apps/addressbase/management/commands/import_uprn_council_lookup.py, polling_stations/apps/addressbase/models.py, polling_stations/apps/addressbase/tests/test_address.py, polling_stations/apps/data_finder/helpers/routing.py
These are mostly piers, and there's only 20 odd of them.
These changes mean that we don't consider them when looking if a
postcode is split, and if all the other addresses in that postcode have
the same council we assume the pier (or lighthouse) is also in that
council.
=> Handle addresses that aren't in a council

polling_stations/apps/data_importers/data_types.py, polling_stations/apps/data_importers/tests/test_address_list.py
The check against addressbase was mutating the list it was iterating
over, meaning duplicate elements weren't all getting deleted, and then
uprns were getting assigned pollingstations, where we weren't confident
of the match.
=> Deal with duplicate elements in addresslist

polling_stations/apps/data_importers/tests/test_teardown.py
CI occasionally falls over because of unsorted lists
=> Sort lists in tests

polling_stations/apps/data_importers/management/commands/import_east_suffolk.py
Notes:
* Wide postcodes NR348ET and IP117RZ are because a property has the wrong address in council data and AddressBase, but it's not going to mislead a user
* Checked polling stations 115 and 56/57/58.
```
Importing data for East Suffolk Council...
----------------------------------
Contextual Data:
Total UPRNs in AddressBase: 134,935
Total Dwellings from 2011 Census: 0
----------------------------------
Addresses: Found 106,049 rows in input file
----------------------------------
WARNING: Polling station 115 is in Ipswich Borough Council (IPS) but target council is East Suffolk Council (ESK) - manual check recommended
WARNING: Polling stations 'St Peters Church Hall St Peters Road' and 'Salvation Army Church & Community Centre 9 Carlton Road' are at approximately the same location, …
```
=> Import East Suffolk

polling_stations/apps/data_importers/management/commands/import_east_devon.py
Few things I thought I should flag:
For some reason `record.addressline6` wasn't picking up postcodes, so I've used `record.post_code`.
Stations 13896 and 13893 share a jumble of addresses in one residential area. This is also the same for stations 13891 and 13632. It's probably fine but just looks a bit strange.
=> import script for east devon (closes #3265)

locale/cy/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po, polling_stations/apps/data_finder/views.py, polling_stations/templates/home.html
Shows the card until 10pm on polling day. Shows "today" instead of the date on polling day itself. All marked for translation, and uses localised date formats and day of week name.
Screenshots with a Welsh `Accept-Language`, but without Welsh translations available:
Polls open tomorrow:
Polls open today:
=> Tidying show_polls_open

polling_stations/apps/data_importers/management/commands/import_portsmouth.py
I added a bit extra to the warnings to contextualise the warnings:
> WARNING: Using UPRN 1775070654 for station ID 4693, but 'PO1 2EZ' != 'PO1 2HH'
> WARNING:   'Cathedral House (Becket Hall), St Thomas`s Street, Portsmouth' vs 'HALL CATHEDRAL HOUSE 63-68 ST THOMAS'S STREET, PORTSMOUTH
> WARNING: Using UPRN 1775073763 for station ID 4704, but 'PO5 4QA' != 'PO5 1EE'
> WARNING:   'King's Church, Somers Road, Southsea' vs 'THE KINGS CHURCH & CENTRE, SOMERS ROAD, SOUTHSEA
> WARNING: Using UPRN 1775037297 for station ID 4722, but 'PO4 0AS' != 'PO4 0AG'
> WARNING:   'Francis Lodge, Fernhurst Junior School, Heidelberg Road, Southsea' vs 'FRANCIS LODGE HEIDELBERG ROAD, SOUTHSEA
> WARNING: Using UPRN 1775106969 for station ID 4730, but 'PO4 9DD' != 'PO4 8AY'
> WARNING:   'St Margaret's Parish …
=> Import Portsmouth (closes #3333)

polling_stations/apps/data_importers/management/commands/import_east_dunbartonshire.py, polling_stations/apps/data_importers/management/commands/import_west_dunbartonshire.py
Also make sure we're only looking at the relevant records per local auth
=> Exclude 'OTHER ELECTOR' rows from Dunbartonshire scripts

polling_stations/templates/fragments/feedback_js.html
Our Welsh translation contains an `'`, which would otherwise break the string quotes.
=> jsescape translation when including in a JS string

polling_stations/templates/fragments/keep_safe.html, polling_stations/templates/home.html
This seems like it might be too many words, interested to hear other's thoughts. As it's below the scroll bar on most screens I don't really mind including it though. I'd be nervous of putting it on the results page as it wouldn't get read at the bottom, and any higher and it would push other stuff way down.
Overview shot of home page: 
This is what the card looks like:
=> Add covid keep safe message

locale/cy/LC_MESSAGES/django.po
The website header at the moment is "Etholiadau6 Mai 2021 ".
It should probably be "Etholiadau 6 Mai 2021".
=> Fix spacing in Welsh string

polling_stations/apps/bug_reports/models.py, polling_stations/apps/bug_reports/templates/bug_reports/disclaimer.html, polling_stations/apps/data_finder/features/index.feature, polling_stations/apps/data_finder/helpers/directions.py, polling_stations/apps/data_finder/tests/test_directions_helper.py, polling_stations/apps/data_finder/tests/test_google_directions.py, polling_stations/apps/data_finder/tests/test_mapbox_directions.py, polling_stations/apps/feedback/templates/feedback/feedback_form.html, polling_stations/templates/base.html, polling_stations/templates/base_full.html, polling_stations/templates/fragments/polling_station_known.html
Three things that improve translations:
* more strings marked for translation
* the "It's about _x_ miles away or a _y_ minute walk/drive from _z_." string creation has been tidied up so it can be translated whole
* likewise with the "get Google / CycleStreets directions" paragraph, as before the "Get … or …" part was untranslatable.
As a side effect, directions handling has been made a bit more verbose, but is hopefully clearer now.
We'll run makemessages on a separate PR, to catch the covid-safe messaging text introduced in #3755.
=> Translation fixes 2021 04 29

locale/cy/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po
This follows up on #3755 and #3756.
It's not quite a straight run of `makemessages --no-wrap`, as it still
wanted to do things slightly differently to Transifex, so I've omitted
the non-substantive reformatting changes introduced by makemessages
alone.
=> Run makemessages, for additional translations

polling_stations/templates/admin/bug_reports/change_list.html, polling_stations/templates/admin/feedback/change_list.html
https://docs.djangoproject.com/en/3.2/releases/2.1/#features-deprecated-in-2-1
=> Django templatetag deprecations

polling_stations/settings/base.py
This is because automatic link checking email systems hit the magic link
and invalidate the token if it's onetime. 2 hrs gives users time to
request a magic link and get a cup of tea.
=> Move to tokens on a 2hr timeout

polling_stations/apps/api/councils.py, polling_stations/apps/api/router.py, polling_stations/apps/api/tests/test_councils.py, requirements/base.txt
This lets us easily import this into a google sheet, in order to keep
track of which councils are live on the site.
=> Add a council csv api endpoint

polling_stations/apps/data_finder/tests/test_views.py, polling_stations/apps/data_finder/views.py, polling_stations/settings/base.py, polling_stations/settings/local.example.py, requirements/base.txt
I'm not logging postcodes that look wrong, and at the moment we only care about postcodes, not addresses. 
We also don't care about API postcodes, as we'll assume they're logged via devs.DC.
Might be of use when working on https://github.com/DemocracyClub/WhoCanIVoteFor/issues/1166
=> Log all postcode lookups

.github/dependabot.yml
AWS releases patch versions of `boto3` on a daily basis, but we don't need to incorporate these changes on the same schedule. This work ensures a dependabot PR will not be raised for patched versions. 
More info https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/
=> Dependabot should ignore boto3 patches

polling_stations/apps/data_importers/management/commands/import_west_lancashire.py, polling_stations/apps/file_uploads/api.py, polling_stations/apps/file_uploads/models.py, polling_stations/apps/file_uploads/templates/file_uploads/email/file_upload_error.txt, polling_stations/apps/file_uploads/templates/file_uploads/email/upload_confirmation.txt, polling_stations/apps/file_uploads/tests/test_api.py, polling_stations/settings/base.py
Closes https://github.com/DemocracyClub/UK-Polling-Stations/issues/4794
Ref https://trello.com/c/M4uUNZMl/3229-priority-wdiv-uploader-fixes-needed-before-next-election
This work:
- sends an email to councils (based on certain EMS uploads) once a file(s) has been uploaded and a PR has been raised
- sends an email to DC if an upload fails
- adds a `reply_to` address has been added to settings
- addresses a deprecation warning with `django.utils.timezone.utc`
=> Send email confirmation to councils following successful upload

locale/cy/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po, polling_stations/templates/fragments/you_dont_need_poll_card.html, polling_stations/templates/home.html
New legislation = new messaging :grin:
NI messaging around voter ID is unchanged but messaging for the other nations has been removed - potentially to be replaced by new messaging when we have that figured out.
=> Remove ID messaging for En/Sc/Cy

deploy/hooks/beforeinstall/initial_setup.sh
We're still getting the dreaded dpkg lock issues randomly tripping up deploys. Let's make sure the apt update has totally finished.
=> Let apt update finish

README.md, polling_stations/apps/file_uploads/models.py, polling_stations/apps/file_uploads/tests/test_utils.py, polling_stations/apps/file_uploads/utils.py, polling_stations/settings/constants/uploads.py
Ref https://github.com/DemocracyClub/UK-Polling-Stations/issues/4220
This work adds a check and alternative route to `assign_council_to_user` when the user wants to login with an email address that contains a domain which differs from the council website domain. 
As noted in the comments, this is a quick fix for the few cases where this need arises; A PR to customise the list will be required as this functionality is not accessible from the admin site. I've added this instruction inline and to the README.
I've tested the following scenarios in the dev server: 
- Login with a standard domain email and be redirected to the matching council
- Login with a custom domain email and be redirected to the designated council
- Try to login with an email address that is neither custom or standard …
=> Assign custom email domains to user

.circleci/config.yml
Ref https://trello.com/c/7Qmm5gtY/3268-make-deploy-fails-more-visible
This work follows on from a sprint retro action to make deploy fails more visible with notifications in Slack. It often happens that we merge work and move the Trello card to done, but then don't notice if a fail occurs on master. 
Testing this work can only be done on master (unless we intentionally build in an error to cause a deploy failure); but the CI should check for the accessibility of the required env variables in the CI organisational settings. That said, we have completed several trial and error commits with the config on WCIVF and this work is based on that learning. 
Confirmation that job and related variables have been found https://app.circleci.com/pipelines/github/DemocracyClub/UK-Polling-Stations/3969/wo …
=> Notify slack on deploy fail

.circleci/config.yml, cdk/lambdas/wdiv-s3-trigger/trigger/handler.py, polling_stations/apps/file_uploads/models.py, polling_stations/apps/file_uploads/templates/file_uploads/council_detail.html, polling_stations/apps/file_uploads/tests/test_api.py
Closes https://github.com/DemocracyClub/UK-Polling-Stations/issues/3051
Ref https://trello.com/c/M4uUNZMl/3229-priority-wdiv-uploader-fixes-needed-before-next-election
- This work adds a status check to each file in the file set during the upload process and returns a more specific status message to the user.
- I've also added a server environment check for prod to send custom error emails as not to confuse anyone in Fresh Desk while we are testing the uploader. 
- Lastly, I've updated the node version in CI as the previous orb was no longer in use. 
Changes can be tested by uploading 1/2 and/or 2/2 EMS files such as http://dev.wdiv.club/uploads/councils/BDF/
REMINDER! Drop this commit once reviewed and approved [12bf87b](https://github.com/DemocracyClub/UK-Polling-Stations/pull/4955/commi …
=> Set status based on EMS and file count

cdk/lambdas/wdiv-s3-trigger/trigger/handler.py, cdk/stacks/wdiv_s3_trigger_stack.py
Ref https://trello.com/c/M4uUNZMl/3229-priority-wdiv-uploader-fixes-needed-before-next-election
Following council uploads for Braintree and Chesire, the upload status was stuck in "Pending" for nearly 24 hours. An error in cloudfront revealed the first issue: 
The councils had uploaded their files at the same time that I had accidentally [pushed a commit ](https://github.com/DemocracyClub/UK-Polling-Stations/commit/4f9ecb8cb375c370f78d350e330bbb01fc96a9bf#diff-eac5b9a79a7241d4d16ae2ffab759d031351fac2218f1b1ec83264311bab6f0fR10 )to master that I thought I had stopped and was later refactored in [this PR](https://github.com/DemocracyClub/UK-Polling-Stations/pull/4955). 
Once we confirmed that both of the council upload files were in S3, we tried the uploader again. 
This resulted in …
=> Get server env from environment

.circleci/config.yml, .circleci/deploy-config.yml, polling_stations/apps/data_importers/base_importers.py, polling_stations/apps/data_importers/management/commands/import.py, polling_stations/apps/data_importers/management/commands/import_malvern_hills.py, polling_stations/apps/data_importers/management/commands/run_new_imports.py, polling_stations/apps/data_importers/tests/test_advance_voting.py, polling_stations/apps/data_importers/tests/test_base_importer.py, polling_stations/apps/data_importers/tests/test_csv_imports.py, polling_stations/apps/data_importers/tests/test_dcounts.py, polling_stations/apps/data_importers/tests/test_district_imports.py, polling_stations/apps/data_importers/tests/test_halarose.py, polling_stations/apps/data_importers/tests/test_run_new_imports.py, polling_stations/apps/data_importers/tests/test_xpress.py, polling_stations/settings/ci.py, polling_stations/settings/constants/importers.py
The aim here is to run import scripts as they get merged in CI 
Closes https://github.com/DemocracyClub/UK-Polling-Stations/issues/4724
https://trello.com/c/0bSKpmSv
`./manage.py run_new_imports -f 4078f6ac -t fcf57110a`
Thoughts on the approach in #x-will. Key point is I made it a management command because it was easier to pinch code from other bits, and seemed better organised and easier to test to me.
```[tasklist]
Check off items once the PR addresses them.
```
=> Run imports in CI

polling_stations/apps/data_finder/views.py
We now log postcodes to the `dc_logging` library and don't need to log in a table per app.
This table is also huge and slows down the replication a lot.
=> Stop logging postcodes to LoggedPostcode table

polling_stations/apps/data_importers/management/commands/import_brighton_hove.py
Correction request from the council
> There’s just one change we’d like to make if possible. It’s for electors in polling district HNPY voting at Community Hall, Downland Court, Stonery Road BN41 2PS. The route takes them to Mile Oak Road – there’s no access this end and electors need to go via Stonery Road to Downland Court. I imagine we can fix this by adjusting the northings and eastings to 525057, 106606. We’ll change it on our end too so it’s fixed for next time.
=> Import script for Brighton and Hove (2023-05-04) (closes #5174)

cdk/lambdas/ssm_run_command_once/command_runner.py, cdk/stacks/command_runner_stack.py, deploy/files/scripts/import_eoni_from_s3.sh, deploy/hooks/afterinstall/system_files.sh, deploy/hooks/beforeinstall/initial_setup.sh, polling_stations/apps/data_importers/management/commands/import_eoni.py, tasks.py
_I have manually run this against the staging RDS_
---
Take the script form the previous deploy and gets it to run using `RunOncePerTagRunCommandClient` (AWS RunCommand).
This is an initial bit of work to get it on staging for them (and us) to QA. We need to figure out how we want to drive this in terms of how we map our staging on to their staging.
Option 1 is that we give them access to the staging bucket and import any data on there in our staging, same for production.
Option 2 is that our staging is only for us, and "production" is the only thing they see. We manage staging imports by giving them access to the production bucket, but import form a "staging" and "production" folder on the bucket. 
I can see some complications with both, but I think option 1 is easier for all of us, …
=> 2023 EONI importer

polling_stations/templates/fragments/polling_station_known.html
Sym reported a bug where NI voters were being told they're allowed to drop their postal vote ballot papers into polling stations. This is not true of NI.
To test locally:
- Have NI data imported
- Search for a postcode you know has an election coming up
- You should no longer see the message "If you have a postal vote, you can hand it in at this polling station on election day up to 10pm"
```[tasklist]
```
=> Remove inaccurate NI postal vote messaging

polling_stations/apps/api/address.py
When we get the EE wrapper we were only using the addresss location when there wasn't a single station for the postcode. However this meant when all addresses vote at a single station, but they are split across wards, we weren't returning the correct ward for an address that was in a different ward to the postcode centroid. With this change we'll still omit an address picker when there should be one, but this endpoint will be right
=> Assume address location on api address view

polling_stations/apps/api/address.py, polling_stations/apps/api/tests/test_postcode.py
This is missing from the API but generally useful to 3rd parties. Especially true now the elections act covers `parl` by-elections
=> Expose `requires_voter_id` from EE in API

polling_stations/apps/data_importers/contexthelpers.py
This is meant to deal with CI failures like this: https://app.circleci.com/pipelines/github/DemocracyClub/UK-Polling-Stations/6014/workflows/b727aa30-ca92-4e74-b80d-e95d100e7e58/jobs/11392?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary
It's also caused import scripts to fail. I don't really understand why requests doesn't just get a http status code. I guess it's something lower level that's failing.
Obviously a bit tricky to test, because it only happens occasionally.
=> Try and handle connection errors from nomisweb.co.uk

polling_stations/apps/file_uploads/templates/file_uploads/upload.html
in almost 100% of cases, councils only have one election. We've just had a complaint about this text, so I am clarifying it (i thought I had previously done this, but obviously not).
=> clarifying upload text for multiple election dates

polling_stations/apps/file_uploads/views.py
https://democracy-club-gp.sentry.io/issues/4998816787/?project=4504713373876224
This is finicky to reproduce. Certainly was occurring in the case where there were stations imported, but no addresses assigned. That was the only configuration that I could come up with. I think I introduced the bug by importing a new `UprnToCouncil` table (i.e. no station's assigned) without tearing down the stations. But then it's occured more than that, but I haven't unpicked exactly why. In any case I think this should stop it.
=> Fix issue when no addresses assigned to station

polling_stations/apps/file_uploads/templates/file_uploads/email/login_message.txt
Some email clients include the full stop in the link. As the end of the URL is the token, this results in URLs like:
`?token=123456.` `123456.` isn't a valid token (`123456` is), so authentication fails.
This change puts the URL on a new line and remove the full stop. This should prevent an (imagined) case where email clients break the link on a new line.
=> Put URL on newline, don't add full stop

polling_stations/apps/file_uploads/templates/file_uploads/upload.html, polling_stations/settings/base.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/local.txt, requirements/testing.txt
- Updates the logo to use s3 url
The dc_utils footer section for logo and copyright, etc should be coming from dc_utils but here it is not and I'm not sure why. It is still working in both languages, in any case.
---
- https://app.asana.com/0/0/1207382614661474
=> Bump dc_utils==6.0.1

polling_stations/apps/api/address.py, polling_stations/apps/api/councils.py, polling_stations/apps/api/postcode.py, polling_stations/apps/data_finder/views.py, polling_stations/settings/constants/councils.py, polling_stations/templates/fragments/polling_station_unknown.html
This allows us to change contact details based on a ballot paper ID.
Designed for short-term patching of councils in Scotland.
=> Initial system for patching council contact details based on election ID

polling_stations/apps/data_importers/ems_importers.py
Currently if a station has a UPRN that isn't in addressbase, halarose scripts will not attempt postcode geocoding. 
This means that sometimes stations will not appear in QGIS even if they have valid postcodes and you pass -p to an import script.
This PR changes the get_station_point method to first try geocoding with the UPRN if it's available and then, if it is allowed, try postcode geocoding if the UPRN fails or is not available.
=> halarose - try postcode geocoding if station uprn fails

polling_stations/apps/data_finder/helpers/every_election.py
Refs https://app.asana.com/0/1204880927741389/1208612753966995/f
This should mean we're not making this query too often, but if we hit a state where we've cached an unhelpful value it won't stick around for an inconveniently long time
=> reduce cache length on election intersecting local auth query

polling_stations/apps/data_finder/helpers/every_election.py
A little something I noticed while working on #8147
This has probably been a bug for a long time
`has_election()` is a method not a property in both classes
so `self.has_election` would have been always evaluating to `True`
=> has_election is a method not a property

cdk/lambdas/wdiv-s3-trigger/tests/test_handler.py, polling_stations/apps/data_importers/management/commands/run_new_imports.py, polling_stations/apps/data_importers/tests/test_run_new_imports.py, polling_stations/settings/base.py
This should fix and issue we were having where dev deploys would 'fail' CI because the 'LAST_IMPORT_SHA' in parameter store had been updated to a value which wasn't in the tree anymore, meaning we couldn't git diff against it.
=> Keep LAST_IMPORT_SHA on master for development env

polling_stations/apps/data_importers/management/commands/import_eoni.py
This hopefully fixes issues like: https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/%2Faws%2Fssm%2Fcommand_runner/log-events/81818ffb-dceb-4a7d-88dd-c43cb743032b%2Fi-07def40bcbc55bf22%2Faws-runShellScript%2Fstdout
I think there might be a separate issue that https://github.com/DemocracyClub/UK-Polling-Stations/pull/8161 addresses - i.e. the sentry reports like: https://democracy-club-gp.sentry.io/issues/5914149783/events/736643c39f84462aa060d54caef2971b/
=> Get object from same database we wrote it to.

deploy/files/conf/crontab
Currently this is chucking a error into Sentry every 5 minutes. In the immediate term, I want it to stop so we don't just use our whole sentry quota logging the same error over and over.
Right now this does not matter as we have `EE_BASE` set to https://elections.democracyclub.org.uk/ However, if we just merge this we will forget it. I'm going to chuck a note in asana to come back to this next sprint.
=> disable sync_elections cron job

cdk/stacks/wdiv_stack.py
This allows Basic Auth in dev and stage.
=> Add Authorization headers to CloudFront

polling_stations/apps/data_importers/management/commands/teardown.py, polling_stations/apps/data_importers/tests/test_teardown.py
This just gives us a short hand way of tearing down the Northern Irish Councils. 
The rational for this is that if there are unexpected scheme changes it would be nice to have a quick way of saying 'we don't know' while we make sure the right data is up.
=> Add flag to teardown NI stations

polling_stations/apps/data_importers/management/commands/import_eoni_from_s3.py, polling_stations/settings/constants/slack.py
The settings object was a LazySettings, and the constants weren't showing up.
I also renamed them to hopefully make typos harder.
=> Fix slack setting in import eoni from s3 cmd

polling_stations/apps/data_importers/management/commands/import_eoni.py
This will probably fix the immediate race conditions we know about, but fundamentally running import scripts from inside a deployed VM (as opposed to CI) is broken by default.
=> Fix EONI import errors

polling_stations/templates/fragments/cancelled_election.html
Refs https://app.asana.com/0/1209332771640377/1209290265508276/f
Refs https://app.asana.com/0/1209332771640377/1209332771640386/f
This is the PR when I am making the most changes.. bit of a general revamp/improvement to the cancelled elections messaging.
I started off thinking the best way to get rid of "cancelled" would be to properly implement cancellations reasons. I've decided that unpicking what is going on with the ballot cache and the 2 different EE backends is just too much to deal with right now. Lets circle back and look at https://app.asana.com/0/1209332771640377/1209332771640406/f after we've re-thought that under the banner of "remove embedded EE". I'm hoping we will simplify a lot of the things that are making this hard in that process :crossed_fingers:
=> revise cancelled elections template

polling_stations/apps/data_importers/management/commands/import_barnet.py
This morning I merged an import script with only data for Barnet's by-election on 2025-02-13
but this removed the previous data for their by-election on 2025-02-13
For now, I'm going to revert that to get the data back up for the one on Thursday
=> revert Barnet import script

polling_stations/apps/dashboard/templates/dashboard/postcode.html
use ds-map-leaflet for polling station dashboard maps, otherwise they won't show up in the postcode view.
=> use ds-map-leaflet for polling station dashboard maps

polling_stations/db_routers.py, polling_stations/settings/base.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt
Refs https://app.asana.com/0/1204880927741389/1208838937595665/f
I'm going to walk through each of the changes in this commit one by one.
This is just a little cleanup of terminology before we start making functional changes. While I was trying to work on this code, I found myself thinking "is the main one default or principal?". Default is sometimes the primary and sometimes the replica, depending on context. I think this makes it clearer what is going on, hopefully :crossed_fingers: 
This is the meat of it really. When we talked about this earlier, we decided an important question was: Does the request detection add much overhead? Essentially, we don't want to add something slow to every round-trip to the DB. Having read over the source of django-middleware-global-request, here's how it …
=> Only serve from replica when there is a request in scope

polling_stations/apps/addressbase/management/commands/create_uprn_council_lookup.py, polling_stations/apps/addressbase/management/commands/import_uprn_council_lookup.py, polling_stations/apps/addressbase/management/commands/update_addressbase.py, polling_stations/apps/addressbase/tests/test_update_addressbase.py, polling_stations/apps/councils/management/commands/import_councils.py, polling_stations/apps/councils/models.py, polling_stations/apps/data_importers/base_importers.py, polling_stations/apps/data_importers/data_quality_report.py, polling_stations/apps/data_importers/data_types.py, polling_stations/apps/data_importers/geo_utils.py, polling_stations/apps/data_importers/management/commands/import_eoni.py, polling_stations/apps/data_importers/management/commands/teardown.py, polling_stations/apps/file_uploads/accessibility_information_handler.py, polling_stations/apps/file_uploads/api.py, polling_stations/apps/file_uploads/models.py, polling_stations/apps/pollingstations/admin.py, polling_stations/apps/pollingstations/tests/test_factories.py, polling_stations/db_routers.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt
Refs https://app.asana.com/0/1204880927741389/1208838937595665/f
This PR is a bit of a mashup of several different things. There are 3 core things I'm doing in this PR.
Prior to #8221 our "solution" to this problem was to pepper `.using()` and `using=` across scripts we thought we might want to run via SSH. #8221 should make this less necessary (but not completely unnecessary - we'll come on to this) so one of the things I'm doing in this PR is removing a lot of that stuff from places where we had done it explicitly and relying on the DB router to route queries to the right DB.
Then that said.. Django's DB routers are a somewhat leaky abstraction. They apply to ORM operations, but that doesn't mean they apply to all database I/O. Specifically there are 2 things we need to worry about: …
=> Explicitly specify DB connection when we need to, and don't when we don't need to

deploy/files/scripts/setup_db_replication.sh, polling_stations/apps/pollingstations/migrations/0013_customfinders.py
Another Django/multiple DBs pitfall.
Here's the sequence of events: In https://github.com/DemocracyClub/UK-Polling-Stations/pull/8214 I deleted the old custom finders model.
After importing ONSPD on prod yesterday, I found that replication wasn't working. Looking a at the logs, https://github.com/DemocracyClub/UK-Polling-Stations/blob/767a02668b35719e7136d74fc478fbd184d4d72c/deploy/files/scripts/setup_db_replication.sh#L27 was failing with `ProgrammingError: relation "pollingstations_customfinder" does not exist` trying to apply `pollingstations.0013_customfinders`
This is kind of a pointless migration because we're inserting records into a table and then later on in the migrations we delete that table. But fundamentally, this migration should apply cleanly to an empty DB. So I wanted to …
=> use the right DB in RunPython migrations

polling_stations/apps/data_importers/ems_importers.py, polling_stations/apps/data_importers/tests/fixtures/halarose_importer/test.csv
Halarose exports seem to have consistent polling station coordinate columns now so we might as well use them if they're populated.
---
- https://app.asana.com/0/0/1209626808958245
=> use coordinate columns from halarose exports

polling_stations/apps/councils/management/commands/import_councils.py, polling_stations/settings/constants/councils.py
This should get us ready to import the new boundaries once the EC updates their API. 
They will get rid of the old districts for Somerset Council and Westmorland and Furness Council, and replace them with a single entry for each. 
---
- https://app.asana.com/0/0/1205086760793639
=> Update council importer 202403

polling_stations/apps/data_importers/ems_importers.py
The way this worked previously, if we had both UPRNs and points we would overwrite with the point from UPRN.
This PR switches it so that we perfer the easting/northing to UPRN if we have both (refs https://github.com/DemocracyClub/UK-Polling-Stations/pull/8328 )
=> halarose base importer: only use uprn if location is null

polling_stations/apps/dashboard/views.py
This is a minor usability thing
Previously, the popups in the maps on the dashboard didn't show the postcodes as part of the address
Now they do
This might not be perfectly formatted in all cases, but its an internal tool so.. meh
=> show postcodes in dashboard maps

deploy/files/conf/crontab, polling_stations/apps/councils/management/commands/import_councils.py, polling_stations/apps/councils/models.py
Refs https://app.asana.com/1/1204880536137786/project/1204880927741389/task/1209717073277337?focus=true
The problems here turned out to be a bit of a mixed bag.
Some of it is stuff I messed up in https://github.com/DemocracyClub/UK-Polling-Stations/pull/8224
Some of it is code that was never doing quite what we thought it was
One of the key things going on here is that there's a number of places where we wrote something like.
```py
thing = Thing.objects.using(db).get_or_create(this='that')
```
From reading the code, I think our assumption/hope was that this would do something like:
```py
try:
thing = Thing.objects.using(db).get(this='that')
except Thing.DoesNotExist:
thing = Thing(this='that')
thing.save(using=db)
```
but it actually behaves more like:
```py
try:
thing = …
```
=> councils app: do all the reads/writes on the right DBs

.pre-commit-config.yaml, polling_stations/apps/addressbase/management/commands/create_dummy_cleaned_addresses_from_onspd.py, polling_stations/apps/data_finder/helpers/geocoders.py, polling_stations/apps/data_finder/tests/playwright/test_postcode_lookup.py, polling_stations/templates/fragments/errors.html, polling_stations/templates/home.html
This gets all the postcodes that aren't in addressbase, aren't large users, and, are on mainland GB (i.e. no Northern Ireland, Channel Islands, Isle of Man) and creates a csv that has the same shape as addressbase_cleaned.csv. However there's a dummy uprn in the form:
ONSPD:TE11ST
Also the address field is blank. This should let us chuck it into the data-baker pipeline to end up in the parquet.
The next step will be to generate the csv and add it to the s3 bucket that databaker produces the parquet files from.
=> Creates a file that looks like addressbase_cleaned.csv from onspd

polling_stations/apps/data_finder/views.py
Sigh
Turns out https://github.com/DemocracyClub/UK-Polling-Stations/pull/8626 was not quite right :see_no_evil: 
The code in that PR dumps the user back to the form with the postcode pre-filled, but if it passes the picture check (regex) but failed geocoding then there's no error set on the form :facepalm: 
Example postcode to test with WV148LF
=> set error on form

cdk/stacks/command_runner_stack.py, deploy/files/scripts/setup_db_replication.sh, polling_stations/apps/core/slack_client.py, polling_stations/apps/core/tests/test_slack_client.py, polling_stations/management/commands/drop_failed_replication_slots.py
Setting up a cron job to drop failed replication slots and report to slack. This will hopefully give us some visibility on the issue, and let us debug it better. It will also stop the stored wal files getting too big and causing problems. 
-----------------
Below this line is not so relevant for the PR as it currently stands.
------------------
When we do more deploys/deploys involving more instances we end up with inactive replication slots on RDS.
These can be seen by running:
```sql
=> select * from pg_replication_slots where active = 'f';
```
Add an `AfterBlockTraffic` hook, and make sure it runs when we drop the instance count in the ASG.
We're running codedeploy blue/green deployments. The order of the hooks in a deployment are described …
=> Add termination hook to deployment group

polling_stations/templates/base.html
This is an example of some wrong code that looked right :facepalm: 
This was actually rendering `<meta name="robots" content="noindex">` on _every_ page
We totally disappeared from the internet
Whoops
=> respect noindex flag
