polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_lambeth.py
Imports data from Lambeth Council.
Also refactors importer classes to give us a clear route to import GEOJson.
=> Lambeth council

polling_stations/assets/css/style.css, polling_stations/templates/about.html, polling_stations/templates/base.html, polling_stations/templates/home.html, polling_stations/templates/navbar.html, polling_stations/templates/postcode_view.html, polling_stations/urls.py
Still needs lots of work but an incremental improvement.
Adds an about page.
=> First pass freshening up the front end.

polling_stations/templates/base.html
=> Adds Google Analytics tracking code to the site

polling_stations/apps/whitelabel/middleware.py, polling_stations/settings/base.py, polling_stations/templates/home.html, polling_stations/templates/postcode_view.html
=> Embed updates

polling_stations/apps/data_collection/management/commands/import_east_riding.py, polling_stations/apps/data_collection/management/commands/import_telford.py, polling_stations/apps/data_collection/management/commands/import_westberks.py
=> Correct inaccurate comments

polling_stations/apps/data_collection/management/commands/import_sheffield.py
=> add import script for Sheffield

polling_stations/apps/data_collection/management/commands/import_watford.py
=> add import script for Watford

polling_stations/apps/data_collection/google_geocoding_api_wrapper.py, polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_dover.py, polling_stations/apps/data_collection/management/commands/import_oadby.py
A few notes on this:
1. I've excluded the proposed polling stations for Oadby & Wigston as none of them have grid references and based on the ids/codes it looks like some of them may be intended to replace existing polling stations. I've modified `import_polling_station_shapefiles()` so it is possible to conditionally ignore records by returning `None` in `station_record_to_dict()`.
2. I've attempted to fill in the missing/invalid postcodes by geocoding, which has helped but there are still some missing postcodes for these councils.
refs #22, #60
=> Import scripts for Dover and Oadby & Wigston

polling_stations/apps/data_collection/management/commands/import_dundee.py
This depends on PR #146 to run under python 3.4, but I've split it out into a separate PR so it is easier to review/merge.
I've not attempted to attach the missing postcodes by geocoding because I think it will probably do more harm than good in this case.
refs #21
=> Import script for Dundee

polling_stations/apps/data_collection/management/commands/import_mid_sussex.py
This depends on PR #146 to run under python 3.4, but I've split it out into a separate PR so it is easier to review/merge.
Closes #64
=> Import script for Mid Sussex

polling_stations/templates/base_embed.html, polling_stations/templates/base_full.html, polling_stations/templates/template.html
Following on from Pull Request #142, I've factored some repeated content out of the base templates. Hopefully this will make them a bit easier to maintain moving forwards.
refs #138
=> Refactor base templates to reduce repitition

polling_stations/apps/data_collection/management/commands/__init__.py
I started writing a few more KML-based import scripts and found myself needing to override `district_record_to_dict()`. This meant I was having to replicate this bit of logic: https://github.com/DemocracyClub/UK-Polling-Stations/blob/master/polling_stations/apps/data_collection/management/commands/__init__.py#L214
I considered factoring it out into a function, but as noted in the comment, this isn't a great solution anyway so it seems like a good time to do something about it. As such, I've modified the base classes to implement a _slightly_ nicer solution.
This probably isn't exactly how I would have ideally done this if I was starting from scratch, but I wanted to avoid breaking all the existing import scripts and having to rewrite/refactor them. Hopefully this represents a reasonable …
=> improve handling of situations where district and station co-ordinates use different srids

polling_stations/apps/data_collection/management/commands/import_plymouth.py
This depends on PR #150 as it uses `get_srid()` but I've kept it on a separate branch to avoid submitting too many things in one PR.
Closes #15
=> Import script for Plymouth

polling_stations/apps/data_collection/management/commands/import_ryedale.py
This depends on PR #150 as it uses `get_srid()` but I've kept it on a separate branch to avoid submitting too many things in one PR.
Closes #20
=> Import script for Ryedale

polling_stations/apps/data_collection/management/commands/import_vale_of_glamorgan.py
This imports the district and station data, but I've not done anything with the UPRNs, as discussed in issue #132.
refs #158, #132
=> Import script for Vale of Glamorgan

polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_kingston.py
Also slight modification to CsvHelper to deal with CSVs that aren't utf-8
Closes #11
=> Import script for Kingston

polling_stations/apps/data_collection/google_geocoding_api_wrapper.py, polling_stations/apps/data_collection/management/commands/import_dover.py, polling_stations/apps/data_collection/management/commands/import_guildford.py, polling_stations/apps/data_collection/management/commands/import_oadby.py, polling_stations/apps/data_collection/management/commands/import_plymouth.py
As I suggested in issue #141, I've added an additional check to the geocoding process allowing us to reject a result which is obviously incorrect.
=> Add additional check to geocoding process

data/W06000004-Denbighshire/PollingStations-2016-02-09.csv, polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_denbighshire.py, polling_stations/apps/pollingstations/migrations/0003_residentialaddress.py, polling_stations/apps/pollingstations/migrations/0004_auto_20160306_1402.py, polling_stations/apps/pollingstations/models.py
This PR defines a structure and a base import class for this type of data. However, additional front-end/UI mods will be needed to use it. I'll add notes under issue #156.
Commit d218be4 is included in PR #160 as well because I found I needed to deal with non-utf-8 encoded CSVs in both import scripts. Hopefully this doesn't complicate the merge.
refs #156
=> Add import script for Denbighshire

polling_stations/apps/nus_wales/templates/nus_wales/base.html, polling_stations/templates/base.html, polling_stations/templates/base_embed.html, polling_stations/templates/coverage.html, polling_stations/templates/data_collection/dataquality_list.html, polling_stations/templates/postcode_view.html
OK, so I've spent this morning really tearing apart the front-end markup and javascript with a HTML validator and JSHint. I've also run through the core user journeys:
* home -> postcode view
* home -> we don't know where you should vote
* home -> address select view -> address view
in the following browsers:
* Firefox
* Chrome (Windows)
* Chrome (Android phone)
* Microsoft Edge (Windows 10)
* IE 11 (Windows 10)
* IE 10 (Windows 7)
* IE 9 (Windows 7)
* IE 8 (Windows 7)
and just for a laugh..
* IE 6 (Windows XP)
I've not tried it in Safari on OSX or iOS though. Can someone else give that a bash?
I was expecting to suggest that we add something like
```
```
but I was actually really surprised at how well the site works even in really old versions of IE (although I wasn't looking for small …
=> Website QA

polling_stations/apps/data_collection/constants.py, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/views.py, polling_stations/templates/postcode_view.html
This adds a line to the map showing routing information. It uses the Google directions API. I've also added a fallback API request to the ORS routing API (for errors, e.g. rate limited). Both can do the time/distance estimate.
Google:
ORS:
=> Routing line on map

polling_stations/templates/postcode_view.html
As David suggested in #74. Copy provisional.
=> Mention polling cards if polling station not known.

polling_stations/apps/data_finder/views.py, polling_stations/apps/pollingstations/models.py
Made a terrible mess of #191 - closing that one. Merge this one instead.
=> Fixed version of 191

polling_stations/apps/data_collection/management/commands/import_dover.py, polling_stations/apps/data_collection/management/commands/import_dundee.py, polling_stations/apps/data_collection/management/commands/import_guildford.py, polling_stations/apps/data_collection/management/commands/import_kingston.py, polling_stations/apps/data_collection/management/commands/import_mid_sussex.py, polling_stations/apps/data_collection/management/commands/import_oadby.py, polling_stations/apps/data_collection/management/commands/import_plymouth.py, polling_stations/apps/data_collection/management/commands/import_sheffield.py, polling_stations/apps/data_collection/management/commands/import_vale_of_glamorgan.py, polling_stations/apps/data_collection/management/commands/import_watford.py
Over the last week or so, we have:
* Fixed a lot of strange behaviour in the `get_polling_station()` logic and template code
* Implemented station_id -> district_id lookup
* Talked a lot about data quality
As a result of all this, I've really understood a lot more about how the finding process works and what conditions in the data shouldn't happen or might cause unintended behaviour to occur. Also, squashing some of the bugs in `get_polling_station()` has helped to provide a front end which makes it much more obvious when strange conditions exist in the data, making problems much easier to find.
Off the back of that, I've done an absolute tonne of testing on the data I've imported since I started working on this and noticed a **lot** of bugs that needed fixing or improvements that could …
=> Change ALL THE THINGS!

polling_stations/apps/data_finder/fixtures/test_routing.json, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests.py, polling_stations/apps/data_finder/tests/test_routing_helper.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/pollingstations/fixtures/test_polling_stations_district_id.json, polling_stations/apps/pollingstations/fixtures/test_polling_stations_polygon.json, polling_stations/apps/pollingstations/fixtures/test_polling_stations_station_id.json, polling_stations/apps/pollingstations/models.py, polling_stations/apps/pollingstations/tests.py, polling_stations/apps/pollingstations/tests/test_polling_station_manager.py
Sorry - this is another PR that changes lots of things in one pull request, but once I started factoring stuff out of the views that didn't need to be there, everything just started coming together so I ran with it..
My original intention was to fix #211 so that I could test #192 properly, fix that, batch those 2 into one pull request and be done with it. Once I did that, I found that I was left with `PostcodeView.get_context_data()` and `AddressView.get_context_data()` doing roughly the same things in different ways (and some more inconsistencies that we hadn't previously spotted) so ended up doing more refactoring.
The net result of all this is:
* It should be easier to make changes to the polling station view without `AddressView` and `PostcodeView` diverging because as much of the …
=> Fix issues #192 and #211 + some refactoring

polling_stations/templates/postcode_view.html
Nice easy one this time :)
Closes #206
=> hide map if location is null

polling_stations/apps/data_collection/management/commands/import_east_riding.py, polling_stations/apps/data_collection/management/commands/import_north_tyneside.py
Some more fixes to import scripts
Refs #216
=> Issue 216 fixes - part 3

polling_stations/apps/data_collection/management/commands/import_ealing.py
Import script for Ealing:
- All districts map to a station, but for some reason there are 5
extra stations mapping to districts we don't have boundaries for
Not sure why, but we have a high level of coverage at any rate
- I haven't attempted to format the addresses/postcodes nicely
because they are so randomly laid out :(
Closes #93
Refs #175
=> Add import script for Ealing

data/W06000003-Conwy/Conwy CBC Polling Stations (with UPRN) 20160407.csv, polling_stations/apps/data_collection/management/commands/import_conwy.py
There is one 'orphan' station:
Neuadd Gymuned Henryd Community Hall
Henryd Road
Henryd
Conwy
maps to non-existant district id 'JB',
but every district has a station assigned to it
Closes #230
=> Import script for Conwy

README.md, polling_stations/apps/data_collection/management/commands/templates/import_geojson_csv.py, polling_stations/apps/data_collection/management/commands/templates/import_kml_csv.py, polling_stations/apps/data_collection/management/commands/templates/import_shape_csv.py, polling_stations/apps/data_collection/management/commands/templates/import_shape_shape.py
A bit of tidying up to reflect recent changes
=> Housekeeping

polling_stations/apps/data_finder/migrations/0001_initial.py, polling_stations/apps/data_finder/migrations/0002_campaignsignup.py, polling_stations/apps/data_finder/models.py, polling_stations/apps/data_finder/views.py, polling_stations/templates/campaign_signup.html, polling_stations/templates/postcode_view.html, polling_stations/urls.py
Signup form applies to DC theme only - not whitelabel/NUS.
Hopefully what I've done with the migrations here is right (apologies - I've not come across squashed migrations before).
I've wrapped all the text up in trans blocks - you may or may not want to see if Gareth can translate them, given this won't show on wheredoivote.wales
Closes #226
=> Add email signup form

polling_stations/apps/nus_wales/templates/nus_wales/base.html, polling_stations/apps/whitelabel/middleware.py
=> English/Cymraeg toggle for NUS Theme

polling_stations/apps/nus_wales/templates/nus_wales/base.html
=> make language links white

polling_stations/apps/data_collection/management/commands/import_southampton.py
=> Import script for Southampton

locale/cy_GB/LC_MESSAGES/django.po, polling_stations/templates/postcode_view.html
Closes #209
This one also requires an additional translation
=> Add date of polling day for EU Ref

README.md, polling_stations/settings/local.example.py
Dunno if this is of interest… One commit fixes typos, the
other suggests using settings/local.py instead of env vars.
=> Update the README and setup vv slightly

polling_stations/api.py, polling_stations/apps/data_finder/migrations/0003_loggedpostcode_language.py, polling_stations/apps/data_finder/models.py, polling_stations/apps/data_finder/views.py
=> Improve logging

polling_stations/apps/pollingstations/admin.py, polling_stations/apps/pollingstations/models.py
=> Add admin interface for CustomFinders

polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_greenwich.py, polling_stations/apps/data_collection/management/commands/import_southwark.py
Based off the Southwark importer, so blocked on that (and that in turn is blocked on addressbase)
Fixes #323
=> Import Greenwich

polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_barking_and_dagenham.py, polling_stations/apps/data_collection/management/commands/import_greenwich.py, polling_stations/apps/data_collection/management/commands/import_southwark.py
Fixes #328 
Based off addressbase PR, do depends on that
=> Import Barking and Dagenham

polling_stations/templates/base_full.html
=> Add a bit more metadata for discoverability

polling_stations/apps/data_finder/views.py, polling_stations/templates/home.html, polling_stations/templates/postcode_view.html
=> validation improvements

polling_stations/api.py, polling_stations/apps/data_finder/forms.py, polling_stations/apps/data_finder/migrations/0004_loggedpostcode_view_used.py, polling_stations/apps/data_finder/models.py, polling_stations/apps/data_finder/views.py, polling_stations/templates/address_select.html, polling_stations/urls.py
Note: this has some text which will need translating for the NUS Wales site
Closes #332
=> Add 'my address is not in the list' button to address select

polling_stations/apps/data_finder/views.py, polling_stations/templates/base_full.html, polling_stations/templates/robots.txt, polling_stations/urls.py
=> Prevent some views from being indexed

polling_stations/apps/data_collection/management/commands/import_epsom_and_ewell.py
=> Import script for Epsom and Ewell

polling_stations/apps/data_collection/management/commands/import_daventry.py
oops :innocent:
This one may need to change again if Joe gets a correction sorted for the duplicate district code.
=> fix Daventry import script

polling_stations/apps/data_collection/management/commands/import_warwick.py
=> Import script for Warwick

polling_stations/apps/data_collection/management/commands/import_cheltenham.py
=> add import script for Cheltenham

polling_stations/apps/data_finder/features/index.feature, polling_stations/apps/data_finder/features/index.py, polling_stations/apps/data_finder/fixtures/test_routing.json, requirements/base.txt, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-my-address-not-in-list/then-i-click-my-address-is-not-in-the-list.yaml
making sure build fails on travis.. tbc
=> Improve acceptance tests

polling_stations/apps/data_collection/management/commands/import_aylesbury_vale.py, polling_stations/apps/data_collection/s3wrapper.py
=> Add import script for Aylesbury Vale

polling_stations/apps/data_collection/management/commands/import_wycombe.py, polling_stations/apps/data_collection/s3wrapper.py
=> Import script for Wycombe

polling_stations/apps/data_collection/management/commands/import_monmouthshire.py, polling_stations/apps/data_collection/s3wrapper.py
=> Import script for Monmouthshire

polling_stations/apps/data_collection/management/commands/import_high_peak.py, polling_stations/apps/data_collection/s3wrapper.py
Based off PR #405
Closes #409
More horrible data..
High Peak did supply a stations file with points but it didn't have any ids to match up to the districts. Both the stations and districts files had addresses (formatted completely differently, of course) so I tried fuzzy matching the 2 sets of addresses but it was all too messy to get full coverage and be confident of the matches.
What I've done is just iterated the districts file twice and used the addresses from that so we won't have maps/directions for this one either :(
=> Import script for High Peak

polling_stations/templates/address_select.html, polling_stations/templates/home.html, polling_stations/templates/postcode_view.html
Based on conversation in #404 - does this seem ok?
=> add archived site notice

polling_stations/apps/data_collection/management/commands/import_redditch.py
=> Import script for Redditch

polling_stations/apps/data_collection/management/commands/import.py
* Now we can run `python manage.py import -r -e 'local.[a-z]+.2017-05-04'` (the `-r` flag tells our script the election id is a regex not a string). Other regular expressions are available, but that is kind of the key one for now :)
* Generally in python we express regular expressions using raw strings, but we have to read this in from the command line so we have to use escaped strings. i.e: `"\\"` not `r"\"`
* There are also some gotchas around using passing certain characters as command line params in bash which can make passing a regex on the command line awkward. Easiest thing is to pass the regex in `'single quotes'` - this will ensure characters like `$ [ ]` etc don't get picked up for variable expansion + so on. Double quotes does not ensure this.
Closes #424
=> Allow bulk import to accept regex

polling_stations/apps/data_collection/management/commands/import_ashfield.py
See comment at top of file for notes
=> Import script for Ashfield

polling_stations/apps/data_collection/management/commands/import_gloucester.py
=> Import script for Gloucester

polling_stations/apps/data_collection/management/commands/import_arun.py
=> Import script for Arun

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/management/commands/__init__.py, polling_stations/apps/data_collection/management/commands/import_aylesbury_vale.py, polling_stations/apps/data_collection/management/commands/import_north_norfolk.py, polling_stations/apps/data_collection/management/commands/import_redditch.py
Added import script for North Norfolk then realised I've written several import scripts recently which are basically all the same so I've added a `BaseXpressCsvImporter` class giving us a general case for data exported from Xpress electoral products. Base class might need a bit more tweaking as we see some more variations, but it is a decent base to start from.
I haven't bothered going back to the scripts from previous elections, but this should make things easier as we get more data of this form.
Closes #443
=> Import script for North Norfolk (+ some generalisation)

polling_stations/apps/data_collection/management/commands/import_swale.py
2 orphan districts on this one where the station is TBC. Have messaged Joe on slack to prod for an update once they're confirmed. Fingers crossed the updated file will be in the same format :crossed_fingers: 
Refs #442 but leave it open pending update
=> Import script for Swale

polling_stations/apps/data_collection/management/commands/import_malvern_hills.py
=> Import script for Malvern Hills

polling_stations/apps/data_collection/management/commands/import_hyndburn.py
=> Import script for Hyndburn

polling_stations/apps/data_collection/management/commands/import_wellingborough.py
=> Import script for Wellingborough

polling_stations/apps/data_collection/management/commands/import_east_northants.py
As noted in slack, there are one or 2 issues for Joe to follow up with the council ;) but I think this is incorporates the right assumptions.
Refs #450 but leave it open pending feedback from East Northamptonshire council
=> Import script for East Northamptonshire

polling_stations/apps/data_collection/management/commands/import_lichfield.py
Lichfield supplied new data in response to our query.
Shoved it on S3, but new data was formatted a bit differently so I had to update the import script slightly. 100% coverage now :)
=> Update Lichfield import script for updated data

polling_stations/apps/api/address.py, polling_stations/apps/api/tests/test_address.py, polling_stations/apps/data_finder/helpers.py
Spotted these when working on PR #465 but these should actually go into master ahead of that.
=> geocode fixes

polling_stations/apps/data_collection/base_importers.py
=> remove debug code I overlooked

polling_stations/apps/data_collection/management/commands/import_coventry.py
=> Import script for Coventry

polling_stations/apps/data_collection/management/commands/import_preston.py
=> Import script for Preston

polling_stations/apps/data_collection/management/commands/import_wychavon.py
=> Import script for Wychavon

polling_stations/apps/data_collection/management/commands/import_oldham.py
=> Import script for Oldham

polling_stations/apps/data_collection/management/commands/import_manchester.py
=> Import script for Manchester

CONTRIBUTING.md
We should have one of those `CONTRIBUTING.md` thingies. Suggest this as a starting point..
Refs #137
=> Proposed contributing guidance

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/management/commands/import_isle_of_wight.py, polling_stations/apps/data_collection/management/commands/import_stockport.py
..and update base importer to deal with polling stations that have no postcode
Closes #477 
Closes #486
=> Import scripts for Isle of Wight and Stockport

polling_stations/apps/data_collection/management/commands/import_crawley.py
=> Import script for Crawley

polling_stations/apps/data_collection/management/commands/import_trafford.py
=> Import script for Trafford

polling_stations/apps/data_collection/management/commands/import_wyre_forest.py
=> Import script for Wyre Forest

polling_stations/apps/data_collection/management/commands/import_conwy.py
Data has not changed. Update election id so it will be included in bulk import
Closes #487
=> Update Conwy election id

polling_stations/apps/data_collection/management/commands/import_fylde.py
=> Import script for Fylde

polling_stations/apps/data_collection/management/commands/import_breckland.py
=> Import script for Breckland

polling_stations/settings/base.py
We're gonna make email great again!
=> make the 'invalid host header' emails stop

polling_stations/apps/data_collection/management/commands/import_mid_sussex.py
..because publishing data in a predictable format is just so predictable
Closes #509
=> update Mid Sussex import script to account for March 2017 data format

polling_stations/apps/data_collection/management/commands/import_aylesbury_vale.py
=> update Aylesbury Vale script for March 2017 data

polling_stations/apps/data_collection/management/commands/import_cotswold.py
=> Import script for Cotswold

polling_stations/apps/data_collection/management/commands/import_pendle.py
=> Import script for Pendle

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/management/commands/import_adur.py, polling_stations/apps/data_collection/management/commands/import_worthing.py
=> Import scripts for Adur and Worthing

polling_stations/apps/data_collection/management/commands/import_denbighshire.py
=> Update Denbighshire import script for 2017 changes

polling_stations/apps/data_collection/management/commands/import_chorley.py
=> Import script for Chorley

polling_stations/apps/data_collection/management/commands/import_fenland.py
=> Import script for Fenland

polling_stations/apps/data_collection/management/commands/import_swansea.py
=> Import script for Swansea

polling_stations/apps/data_collection/management/commands/import_huntingdonshire.py
=> Import script for Huntingdonshire

polling_stations/apps/data_finder/views.py, polling_stations/urls.py
=> allow /postcode endpoint to optionally accept postcode as GET param

polling_stations/apps/api/address.py, polling_stations/apps/api/postcode.py, polling_stations/apps/api/tests/test_postcode.py, polling_stations/templates/api_docs/README.md, polling_stations/templates/api_docs/blueprints/finder.apibp, polling_stations/templates/api_docs/blueprints/finder_responses/schema.apibp, polling_stations/templates/api_docs/html/docs.html
After I closed #550 I spotted there were a couple of API improvements in it that were relevant regardless, so I've pulled those out into here.
Closes #531
=> API tweaks

polling_stations/apps/data_collection/management/commands/import_tendring.py
3 oprhan districts:
* AW - West Cliff
* CV - Lawford West
* CR - Tollgate
Rest of the data is fine. I've asked Joe to follow up with contact at Tendring council. If they let us know, I can update it. If not we have coverage for all but 3 districts.
Refs #518
=> Import script for Tendring

polling_stations/apps/data_finder/context_processors.py, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_helpers.py, polling_stations/settings/base.py, polling_stations/settings/constants/example_postcode.py, polling_stations/templates/home.html, polling_stations/templates/postcode_view.html
See #575 for comments. This is really a tiny start at the work needed, but it gets it done quickly and in more or less a future proof way (I think).
=> Example postcode helper class

polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/views.py, polling_stations/templates/postcode_view.html, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-invalid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-valid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-without-address-picker/then-i-submit-the-only-form.yaml
=> Use point for directions origin, not postcode

polling_stations/apps/data_collection/management/commands/import_oldham.py
=> update Oldham import script

polling_stations/apps/data_collection/management/commands/import_tendring.py
All issues now resolved.
Closes #518
=> update Tendring import script

polling_stations/apps/data_collection/management/commands/import_epsom_and_ewell.py
=> exclude duplicate/ambiguous district codes in epsom+ewell import

polling_stations/apps/data_collection/management/commands/import_dover.py
=> Fix Dover import script

polling_stations/apps/data_collection/management/commands/import_cambridge.py
=> Import script for Cambridge

polling_stations/apps/data_collection/management/commands/import_gravesham.py
=> Import script for Gravesham

polling_stations/apps/data_collection/management/commands/import_craven.py, polling_stations/apps/data_collection/management/commands/import_hartlepool.py, polling_stations/apps/data_collection/management/commands/import_norwich.py, polling_stations/apps/data_collection/management/commands/import_rochdale.py, polling_stations/apps/data_collection/management/commands/import_south_ribble.py, polling_stations/apps/data_collection/management/commands/import_swale.py, polling_stations/apps/data_collection/management/commands/import_wigan.py
Can't be bothered doing individual PRs
Closes #572
Closes #577
Closes #578
Closes #595
Closes #599
Closes #618
=> Pile of import scripts

polling_stations/apps/data_collection/management/commands/import_exeter.py
=> Import script for Exeter

polling_stations/apps/data_collection/management/commands/import_wigan.py
=> Update Wigan data

polling_stations/apps/data_collection/morph_importer.py
As noted elsewhere, OS X will always fail to open and data the first
time ¯\_(ツ)_/¯
=> Fix OS X bug with DataSource

polling_stations/apps/data_collection/management/commands/import_canterbury.py
=> Import script for Canterbury

polling_stations/apps/data_collection/management/commands/import_doncaster.py
=> Import script for Doncaster

polling_stations/apps/data_collection/management/commands/import_shepway.py
=> Import script for Shepway

polling_stations/apps/data_collection/management/commands/import_hastings.py
=> Import script for Hastings

polling_stations/apps/data_collection/management/commands/import_cotswold.py
=> Update Cotswold import script

polling_stations/apps/data_collection/management/commands/import_craven.py, polling_stations/apps/data_collection/management/commands/import_harrogate.py, polling_stations/apps/data_collection/management/commands/import_new_forest.py, polling_stations/apps/data_collection/management/commands/import_thanet.py
Closes #472
Closes #566
Closes #600
=> various import scripts

polling_stations/apps/data_collection/management/commands/import_basildon.py, polling_stations/apps/data_collection/management/commands/import_bury.py, polling_stations/apps/data_collection/management/commands/import_gravesham.py, polling_stations/apps/data_collection/management/commands/import_manchester.py, polling_stations/apps/data_collection/management/commands/import_north_kesteven.py, polling_stations/apps/data_collection/management/commands/import_sandwell.py, polling_stations/apps/data_collection/management/commands/import_south_hams.py, polling_stations/apps/data_collection/management/commands/import_suffolk_coastal.py
Easy wins
Closes #656
Closes #655
Closes #654
Closes #652
Closes #646
Closes #639
Closes #597
Closes #585
=> Bunch of import scripts

polling_stations/apps/data_collection/management/commands/teardown.py
Remove data for just one council:
`./manage.py teardown -c W06000011`
Remove data for all councils:
`./manage.py teardown --all`
Closes #131
Closes #648
=> Allow teardown to accept council id as param

polling_stations/urls.py
=> Remove Django admin

polling_stations/apps/data_collection/management/commands/import_ashfield.py, polling_stations/apps/data_collection/management/commands/import_hertsmere.py
=> Import scripts

polling_stations/apps/data_collection/management/commands/import_mid_sussex.py
=> convert Mid Sussex script to use Xpress export

polling_stations/apps/data_collection/management/commands/import_daventry.py
=> fix Daventry import script (again)

polling_stations/apps/data_collection/management/commands/import_daventry.py, polling_stations/apps/data_collection/management/commands/import_hart.py
=> remove election ids from Hart and Daventry

polling_stations/apps/data_collection/management/commands/import_rochdale.py
=> update Roachdale import script

polling_stations/apps/data_collection/management/commands/import_daventry.py
=> update Daventry import script for new data format

polling_stations/apps/addressbase/helpers.py
I ran another `imported-db` build earlier today. It took ages. This will not be improved once I start working through all the Scotland data next week (it is all shp files), so I decided to see if I could improve efficiency some more. The slowest part of the import script is finding all the postcodes which contain UPRNs in >1 polling district and assigning each UPRN a polling station, so I've focussed my efforts there.
The main problem was that `EdgeCaseFixer.make_addresses_for_postcode()` was running a minimum of 2 DB queries per address - sometimes more. I've modified this so that now we perform one giant DB query per postcode which returns all the information we need for all the addresses in that postcode. This massively reduces the amount of time each script/thread spends performing …
=> Improve import script performance

polling_stations/templates/multiple_councils.html, polling_stations/templates/postcode_view.html
Deadline for Scotland is Monday so I'll merge + deploy this next week
=> remove register to vote card

polling_stations/apps/data_collection/management/commands/import_daventry.py, polling_stations/apps/data_collection/management/commands/import_harrogate.py, polling_stations/apps/data_collection/management/commands/import_hertsmere.py
sometimes its a `str`, sometimes its a `bytes`..
sometimes it converts nicely, sometimes it doesn't..
=> fix various str/bytes issues in import scripts

CONTRIBUTING.md, README.md
Given we've had a number of people express interest in helping us recently, it would be useful if following the setup process resulted in a working local install rather than confusing error message
=> Update setup info

polling_stations/apps/data_collection/management/commands/import_leeds.py, polling_stations/apps/data_collection/management/commands/import_york.py
Already on the road to `parl.2017-06-08`..
Closes  #705
=> tag Leeds and York with 'parl.2017-06-08'

polling_stations/apps/data_collection/management/commands/import_st_albans.py
Have queried one orphan district. If they update their API, we'll pick it up and re-run
Closes #716
=> Import script for St Albans

polling_stations/apps/data_collection/management/commands/import_tonbridge.py
Doing this for now so I can get a data build started. Will get an actual fix done later..
=> remove Tonbridge and Malling election ID (for now)

polling_stations/apps/api/postcode.py
=> remove non-alphanumeric chars in postcode api calls

polling_stations/templates/multiple_councils.html, polling_stations/templates/postcode_view.html, polling_stations/templates/sidebar/register_to_vote.html
Based on the text from https://www.gov.uk/register-to-vote
Tried an alternative layout with the text from http://www.electoralcommission.org.uk/i-am-a/voter but it was too long/wordy
=> new register to vote card for GE2017

polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_ee_wrapper.py, polling_stations/apps/data_finder/views.py, polling_stations/settings/base.py, polling_stations/templates/election_explainers.html, polling_stations/templates/postcode_view.html, requirements/base.txt
This PR goes hand-in-hand with https://github.com/DemocracyClub/EveryElection/pull/28 It is designed such that if EE is not returning explainers, it won't fall over but it is still probably worth co-ordinating the two. If I make changes to one they may need to be reflected in the other. I'll leave it WIP pending review of https://github.com/DemocracyClub/EveryElection/pull/28
A couple of notes/questions:
1. I've chosen to only show the explainers card when:
* Polling station is found
* Brand is DemocracyClub (i.e: not in the embedded version)
Are these the correct decisions?
2. Here's an example of what the output might look like for an area with multiple elections if `get_explanations()` were to return
```
[
"""
On 4 May 2017 you will elect your county councillor in a [first past the …
```
=> Consume Election Explainers data from Every Election

polling_stations/settings/base.py, polling_stations/settings/constants/directions.py
Not the neatest way of doing it, but needs fixing sooner rather than later
=> actually use directions API key

polling_stations/apps/addressbase/helpers.py
If we hit a point which is not contained by the boundary of any council object:
- Try to look up the UPRN in the ONSAD
- If that also fails, handle it by skipping the address and logging a warning (instead of raising)
...because piers and stuff
=> Deal with points not contained by any council boundary

polling_stations/templates/home.html
Find your polling station, not Find your Polling Station
Enter your postcode, not Enter Your Postcode
=> Transform to sentence case

polling_stations/templates/postcode_view.html
=> add note saying stations may change between May and June

polling_stations/apps/addressbase/helpers.py
Use ONSAD to determine local auth in preference to `ST_COVERS()`. Only fall back to geo lookup if UPRN is not in the ONSAD.
Refs #743 but I'm not going to close it because there's probably more we can do to improve performance. This one change is probably the largest gain we can make here though.
=> Improve bulk import performance

polling_stations/apps/data_collection/management/commands/import_sevenoaks.py
=> update Sevenoaks import script

polling_stations/templates/robots.txt
..but keep the docs and index visible to bots/spiders
Closes #683
=> disallow api endpoints in robots.txt

polling_stations/apps/pollingstations/models.py
.. I really thought we were already doing this! (eek)
=> Say "we don't know" if districts overlap

polling_stations/apps/data_collection/management/commands/import_ceredigion.py
Ceredigion, you shall go to the ball!
=> update Ceredigion import script

polling_stations/templates/sidebar/register_to_vote.html
Reference local election stuff first and then general election stuff
=> put points on 'register to vote' card in chronological order

polling_stations/settings/constants/elections.py, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-invalid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-valid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-without-address-picker/then-i-submit-the-only-form.yaml
=> switch to elections2

polling_stations/apps/data_collection/management/commands/import_lancaster.py
> Barton Road Community Centre LA1 4ER is not a polling station this year. Folk who normally vote there are going to Moorside School.
.. but @polling-bot-4000 was already on the case :)
=> update Lancaster import script

polling_stations/apps/data_finder/helpers.py
Hopefully 3e21015 is sort of shutting the door after the horse has bolted, but this will ensure that if Every Election dies, WhereDIV can move on.
9d0cade makes it easier to for us to track our own API usage internally.
Refs #767
=> Use timeout and custom UA when calling EE

polling_stations/templates/base_full.html, polling_stations/templates/postcode_view.html, polling_stations/templates/sidebar/register_to_vote.html, polling_stations/templates/sidebar/you_dont_need_poll_card.html
Various copy/text edits
Closes #752
=> Switch focus of site from local elections to general election

polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_collection/management/commands/import_lancaster.py
tiny payment on the mountain of tech debt
=>  Allow station_record_to_dict to return a list containing None

polling_stations/apps/data_collection/management/commands/import_barrow_in_furness.py, polling_stations/apps/data_collection/management/commands/import_bristol.py, polling_stations/apps/data_collection/management/commands/import_canterbury.py, polling_stations/apps/data_collection/management/commands/import_doncaster.py, polling_stations/apps/data_collection/management/commands/import_dover.py, polling_stations/apps/data_collection/management/commands/import_dundee.py, polling_stations/apps/data_collection/management/commands/import_eden.py, polling_stations/apps/data_collection/management/commands/import_edinburgh.py, polling_stations/apps/data_collection/management/commands/import_epsom_and_ewell.py, polling_stations/apps/data_collection/management/commands/import_fife.py, polling_stations/apps/data_collection/management/commands/import_guildford.py, polling_stations/apps/data_collection/management/commands/import_hastings.py, polling_stations/apps/data_collection/management/commands/import_lancaster.py, polling_stations/apps/data_collection/management/commands/import_runnymede.py, polling_stations/apps/data_collection/management/commands/import_salford.py, polling_stations/apps/data_collection/management/commands/import_shepway.py, polling_stations/apps/data_collection/management/commands/import_st_albans.py, polling_stations/apps/data_collection/management/commands/import_thanet.py, polling_stations/apps/data_collection/management/commands/import_tonbridge.py, polling_stations/apps/data_collection/management/commands/import_tunbridge_wells.py, polling_stations/apps/data_collection/management/commands/import_wellingborough.py, polling_stations/apps/data_collection/management/commands/import_wolverhampton.py
=> update all API import script with parl.2017-06-08 election id

polling_stations/apps/data_collection/management/commands/misc_fixes.py
..because we've removed the entire import script
=> Remove Wealden 'misc fix'

polling_stations/settings/constants/elections.py, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-invalid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-valid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-without-address-picker/then-i-submit-the-only-form.yaml
Revert "switch to elections2 and update tests"
This reverts commit c548cdab8001423d4e02f31783536e258234bd41.
=> Switch back to elections.dc

polling_stations/apps/data_collection/data_types.py, polling_stations/apps/data_collection/tests/test_address_set.py
Closes #812
several `TODO`s here but this will plug the gap for now
=> Remove ambiguous addresses more aggressively

polling_stations/apps/addressbase/management/commands/import_onsad.py
import any CSV files in this directory because we can't rely on them to be consistently named
vaguely related to #820 but doesn't fix it
=> fix ONSAD/ONSUD import

polling_stations/templates/postcode_view.html
Desktop: full zoomy/draggy-ness
Mobile: 1 finger scroll, 2 finger zoom/drag
Closes #763
=> Map scrolling changes

polling_stations/apps/feedback/admin.py, polling_stations/apps/feedback/apps.py, polling_stations/apps/feedback/context_processors.py, polling_stations/apps/feedback/forms.py, polling_stations/apps/feedback/migrations/0001_initial.py, polling_stations/apps/feedback/models.py, polling_stations/apps/feedback/templates/feedback/feedback_form.html, polling_stations/apps/feedback/templates/feedback/feedback_form_view.html, polling_stations/apps/feedback/templates/feedback/feedback_js.html, polling_stations/apps/feedback/urls.py, polling_stations/apps/feedback/views.py, polling_stations/db_routers.py, polling_stations/settings/base.py, polling_stations/templates/postcode_view.html, polling_stations/urls.py
This is roughly nicked from https://github.com/DemocracyClub/WhoCanIVoteFor/tree/master/wcivf/apps/feedback with a few tweaks. Some notes (partly for my own reference when I come to tidy this up in future):
1. I've gone with "Did you find this useful?" rather than "Did you find what you were looking for?" as I think WhereDIV answers a more focussed question than WhoCIVF. People might go to WhoCIVF looking for many things whereas there's really only one piece of information you want from WhereDIV - it is whether we did a good job of presenting it we probably need feedback on.
2. I've intentionally just inlined the JS because I can't be bothered to think about reviewing our approach to JS loaders and static asset pilelines and things at the moment but I do want to think about that in more …
=> Add 'did you find this useful' feedback form

polling_stations/templates/custom_finder.html, polling_stations/templates/postcode_view.html
=> show NI users EONI contact info

polling_stations/apps/data_collection/management/commands/misc_fixes.py
We've reported to Ordnance Survey but no corrections issued
We can't manually fix, but we can remove
=> remove some known bad data points in AddressBase

polling_stations/apps/data_collection/management/commands/import_newport.py, polling_stations/apps/data_collection/management/commands/import_wandsworth.py
Reported problems in both of these areas
=> Remove some ropey data

polling_stations/apps/data_collection/management/commands/misc_fixes.py
following feedback from Reading
=> fix address and point for Tilehurst Vilage Hall

polling_stations/apps/data_collection/management/commands/misc_fixes.py
`misc_fixes.py` is rapidly becoming my least favourite file in this repository
=> ad-hoc fixes for issues reported by users

polling_stations/apps/data_collection/management/commands/misc_fixes.py
Sutton
Milton Keynes
Calderdale
Camden
Islington
=> misc ad-hoc fixes

polling_stations/templates/address_select.html, polling_stations/templates/archived_site.html, polling_stations/templates/base_full.html, polling_stations/templates/home.html, polling_stations/templates/postcode_view.html, polling_stations/templates/sidebar/register_to_vote.html, polling_stations/templates/sidebar/you_dont_need_poll_card.html
=> Shut it Down

polling_stations/apps/data_finder/helpers.py, polling_stations/settings/base.py, polling_stations/settings/constants/directions.py
Tidy up the hack in #737 a bit
=> assemble directions URL in nicer way

polling_stations/apps/addressbase/helpers.py, polling_stations/apps/api/postcode.py, polling_stations/apps/data_collection/base_importers.py, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/pollingstations/helpers.py, polling_stations/apps/pollingstations/models.py, polling_stations/apps/pollingstations/tests/test_postcode_helpers.py
Lets see if we can put an end to the postcode formatting madness
I've tested this but this change touches so many important things I bet it breaks something that I have not spotted. Hopefully if we do this now I will work out what that is when we're not in the grip of a really important election :)
Closes #678
=> use consistent postcode formatting functions

polling_stations/apps/data_collection/data_types.py, polling_stations/apps/data_collection/tests/test_address_set.py
PR #818 was done in a bit of a rush. This PR adds some additional test cases and a bit of refactoring to (hopefully) make the logic a bit clearer
=> Tidy up code for handling ambiguous addresses

polling_stations/apps/api/postcode.py, polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/views.py
- Factor out `get_council()` logic into a helper function
- Call that function in API code and website code so we always get the same result
Closes #999
=> work out user's council consistently in api and front-end

polling_stations/apps/addressbase/management/commands/import_onsad.py, polling_stations/apps/addressbase/migrations/0004_onsad_ctry_flag.py, polling_stations/apps/addressbase/models.py
July ONSUD release adds a new column we need to import
=> update for July changes to ONSUD

polling_stations/templates/address_select.html, polling_stations/templates/home.html, polling_stations/templates/postcode_view.html
next time we deploy we won't be serving old data
=> remove archived site banners

polling_stations/templates/sidebar/you_dont_need_poll_card.html
- explain you must vote at your assigned station
- clarify you need to be registered
Closes #1055
Closes #1056
=> copy edits

polling_stations/assets/custom_js/map.js
=> Ensure icons are always inside viewport

polling_stations/apps/pollingstations/context_processors.py, polling_stations/settings/base.py, polling_stations/settings/testing.py, polling_stations/templates/base.html
=> don't log to google analytics when running integration tests

.travis.yml
Put the `before_cache` block before the `cache` block and the `before_script` block before the `script` block..
No functional changes
=> re-organise travis.yml into sane order

polling_stations/apps/api/address.py
fixes `'str' object has no attribute 'without_space'`
oops
=> cast to Postcode before loggging

.pyup.yml, polling_stations/apps/data_collection/views.py, polling_stations/apps/data_finder/features/index.py, polling_stations/apps/data_finder/features/smoke_tests.feature, polling_stations/apps/data_finder/views.py, requirements/base.txt, requirements/jenkins.txt, requirements/production.txt, requirements/testing.txt
I've been intending to
* prune unnecessary dependencies from our requirements files and
* do a better job of keeping our dependencies up-to-date
for some time. It occurrs to me that upgrading loads of packages now is probably a good idea - as opposed to, for example, in April. We're not in 'critial' deployment and if I'm doing a load of work on the site locally, I should hopefully pick up anything subtle that has been missed in the tests. To keep us on track moving forwards, I've pinned everything to the latest version (or latest version we can use with django 1.8 in some cases*) and I want to add [PyUpBot](https://pyup.io/) to the repo. PyUpBot will monitor our dependencies and every time a new version of a library we are using is release it will submit a PR [like …
=> update ALL THE PACKAGES

package.json, polling_stations/settings/static_files.py
Tried this locally and it seems to work fine. Not sure why I went with the 1.x branch in the end - maybe I was just sick of minifiers by that time and found something that worked.
Either way, I'll make a note to check it on a staging build next time I deploy just to be sure.
=> upgrade uglify-js

polling_stations/apps/data_collection/ems_importers.py
It is relatively unusual, but if we've got a station UPRN but no grid ref, try UPRN to geocode in preference to postcode so we have a more accurate point if possible.
Closes #1039
=> Use station UPRN in Xpress importers

polling_stations/apps/data_collection/base_importers.py
This is a really obvious bit of information to show at import script time: the rows found in the input file (for comparison against the number of rows we inserted into the DB). I usually just check against the input file, but showing it inline will be helpful.
The other significant thing this does is add the `BaseImporter.write_info()` method which we can use to print handy contextual info like this that should be shown when the verbsoity level is 1 or higher but we don't want to raise a `logging.WARNING` level event because we aren't warning about anything. This will be useful when addressing some of the other points in #1045
=> show rows/features found at start of import script

polling_stations/apps/data_collection/management/commands/import_vale_of_glamorgan.py, polling_stations/apps/data_collection/management/commands/import_westminster.py, polling_stations/apps/pollingstations/admin.py, polling_stations/settings/base.py
Fixed a few small errors/warnings picked up by running the code through LGTM: https://lgtm.com/projects/g/DemocracyClub/UK-Polling-Stations/alerts/?mode=list
=> Fix issues picked up by static analysis

.travis.yml, polling_stations/apps/data_collection/urls.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/feedback/urls.py, polling_stations/apps/pollingstations/tests/test_urls.py, polling_stations/apps/uk_geo_utils/tests/test_centroid.py, polling_stations/apps/whitelabel/urls.py, polling_stations/settings/base.py, polling_stations/settings/testing.py, polling_stations/urls.py, requirements/base.txt, tox.ini
Not ready for review yet..
Refs #1092
=> upgrade to Django 1.11

requirements/base.txt
see http://initd.org/psycopg/docs/install.html#binary-install-from-pypi
=> switch to psycopg2-binary 2.7.4

polling_stations/apps/data_collection/ems_importers.py, polling_stations/apps/data_collection/tests/fixtures/dcounts_importer/districts.csv, polling_stations/apps/data_collection/tests/fixtures/dcounts_importer/stations.csv, polling_stations/apps/data_collection/tests/fixtures/halarose_importer/test.csv, polling_stations/apps/data_collection/tests/fixtures/xpress_importer/test_ambiguous.csv, polling_stations/apps/data_collection/tests/fixtures/xpress_importer/test_democlub.csv, polling_stations/apps/data_collection/tests/fixtures/xpress_importer/test_weblookup.csv, polling_stations/apps/data_collection/tests/stubs/stub_dcountsimport.py, polling_stations/apps/data_collection/tests/stubs/stub_halaroseimport.py, polling_stations/apps/data_collection/tests/stubs/stub_xpress_democlub.py, polling_stations/apps/data_collection/tests/stubs/stub_xpress_weblookup.py, polling_stations/apps/data_collection/tests/test_dcounts.py, polling_stations/apps/data_collection/tests/test_halarose.py, polling_stations/apps/data_collection/tests/test_importers.py, polling_stations/apps/data_collection/tests/test_xpress.py
=> Tests for EMS import classes

polling_stations/apps/data_collection/addresshelpers.py, polling_stations/apps/data_collection/ems_importers.py, polling_stations/apps/data_collection/management/commands/import_north_tyneside.py, polling_stations/apps/data_collection/tests/test_halarose.py
Probably should have done this ages ago
=> refactor address formatting functions, import North Tyneside

polling_stations/apps/data_collection/management/commands/import_havant.py
=> import script for Havant

polling_stations/apps/feedback/views.py
=> pass token when creating Feedback object

polling_stations/apps/data_collection/data_types.py
Remove any addresses with a postcode which appears in our input data but where the postcode centroid is outside the target local auth.
If we've got records in the input file with a postcode centroid outside the target local auth this either indicates:
* A mistake (in which case we want to remove this bad data), or
* This is legit data but the postcode is split across multiple local authorities (in which case we just show the multiple_councils view, even if we hold data).
In either case, we might as well bin the data at import time.
@symroe - if you get a chance to review this before I next deploy later in the week, sanity check would be useful. If not, I'll just crack on and merge it.
There will inevitably be some edge cases on the edge of this edge case e.g:
* Postcodes which do exist in …
=> discard addresses outside target local auth

polling_stations/templates/api_docs/blueprints/councils.apibp, polling_stations/templates/api_docs/blueprints/finder.apibp, polling_stations/templates/api_docs/blueprints/pollingdistricts.apibp, polling_stations/templates/api_docs/blueprints/pollingstations.apibp
RFC 7946 replaces the old 2008 spec
=> replace links to geojson.org with links to RFC 7946 in api docs

polling_stations/apps/data_collection/management/commands/import_bexley.py
=> correction to Bexley import script

polling_stations/templates/base.html
seems like a thing we should do
=> link to API in footer

polling_stations/templates/postcode_view.html
Deadline is 17th April
/remind me "merge this pull request" on 18th April
=> remove 'register to vote' card

polling_stations/apps/data_finder/helpers.py, polling_stations/apps/data_finder/tests/test_ee_wrapper.py, polling_stations/settings/constants/elections.py
allows us to deal with uncontested seats and last-minute cancellations
=> add election blacklist

polling_stations/apps/data_collection/management/commands/misc_fixes.py
doing this one like this as an excuse to test deploying an ad-hoc fix
=> misc fixes

polling_stations/apps/data_collection/management/commands/import_waltham_forest.py
=> update Waltham Forest import script

polling_stations/apps/data_collection/management/commands/misc_fixes.py
2 from users
2 from local auth
=> grid reference corrections

polling_stations/templates/api_docs/blueprints/finder.apibp, polling_stations/templates/base_full.html, polling_stations/templates/fragments/polling_station_known.html, polling_stations/templates/fragments/polling_station_unknown.html, polling_stations/templates/fragments/register_to_vote.html, polling_stations/templates/postcode_view.html
its all over :chart_with_downwards_trend: 
as you were
=> remove 2018 local election content

polling_stations/apps/data_collection/filehelpers.py, polling_stations/apps/data_collection/github_importer.py
Django 1.11 contains a bugfix for the issue this was a workaround for
=> remove DataSource() constructor hack

polling_stations/apps/api/docs.py, polling_stations/urls.py
As noted during theme upgrade, the router isn't a good place for this info to live.
=> define api docs params in a view class

polling_stations/apps/data_collection/ems_importers.py
If there are multiple options available for location data in a file, this makes it easier to understand how we arrived at each grid ref.
closes #1370
=> add logging events to BaseXpressCsvImporter.get_station_point

.travis.yml
=> alow greenkeeper bot to update lockfile

polling_stations/apps/data_collection/management/commands/import_preston.py
Preston have set up a WFS server so we can yoink data from there in future :)
=> import data from Preston's WFS server

polling_stations/apps/data_finder/middleware.py, polling_stations/apps/pollingstations/context_processors.py, polling_stations/apps/pollingstations/middleware.py, polling_stations/apps/whitelabel/middleware.py, polling_stations/settings/base.py, polling_stations/templates/base.html, requirements/base.txt
This basically applies the same changes I made in
https://github.com/DemocracyClub/EveryElection/pull/381 and https://github.com/DemocracyClub/EveryElection/pull/383
to WhereDIV.. except I needed to do a bit of additional middleware faffing to get it all to work nicely :)
=> Staging deploy improvements

polling_stations/apps/data_collection/management/commands/import_broxtowe.py, polling_stations/apps/data_collection/management/commands/import_moray.py, polling_stations/apps/data_collection/management/commands/import_perth_and_kinross.py
Added import scripts (with no election ids attached to them) for a couple of local auths who publish data. Hopefully doing a bit of work now might save us some time at a pinch point.
The other 2 I found (Perth & Kinross, South Ayrshire) had some problems with the data so I've decided not to spend a lot of time on trying to work out issues specific to old data. We'll follow those up if/when necessary. We will at least get notifications if/when the data changes :)
=> import scripts for Broxtowe and Moray

requirements/production.txt
For some reason Pyup pushed this to a branch but didn't open a PR :confused: 
Its opened a PR on EE today. I'll have to keep an eye on it. If it persists I'll raise a support ticket
=> Update gunicorn from 19.8.1 to 19.9.0

.coveragerc
oops: coverage decreased (-26.8%) to 44.169%
=> ignore .tox in coverage

polling_stations/apps/api/address.py, polling_stations/apps/api/postcode.py, polling_stations/apps/api/tests/mocks.py, polling_stations/apps/api/tests/test_address.py, polling_stations/apps/api/tests/test_postcode.py, polling_stations/apps/data_finder/helpers/every_election.py
* serve up ballot info (with `all_future_ballots` flag for next date/all future)
* update tests
TODO:
* update API docs
=> expose ballot info in API 

polling_stations/apps/data_collection/base_importers.py
refs #1457
we're going to be using a subset of AddressBase Premium moving forwards..
=> minor text edit AddressBase Standard --> AddressBase

polling_stations/apps/pollingstations/context_processors.py, polling_stations/settings/base.py, polling_stations/templates/base.html, requirements/base.txt, requirements/production.txt
closes #1135
refs https://github.com/DemocracyClub/polling_deploy/pull/160
=> send javascript errors to sentry

polling_stations/apps/data_collection/ems_importers.py, polling_stations/apps/data_collection/management/commands/import_kirklees.py
closes #1463
closes #1465
These 2 issues aren't strictly related, but they both involved changing the same function so I just loaded them into one PR
=> more lenient station UPRN validation in Xpress importer, flag on Xpress base importer to control fallback to postcode

polling_stations/apps/data_collection/ems_importers.py
=> more extraneous whitespace removal

polling_stations/apps/data_collection/management/commands/import_epsom_and_ewell.py
=> import Epsom & Ewell

polling_stations/apps/data_collection/management/commands/import_redcar_cleveland.py
I actually don't want to deploy this one until we've followed up a query with them :man_facepalming:
=> remove election id from Redcar & Cleveland import script

polling_stations/apps/data_collection/management/commands/import_redcar_cleveland.py
wait on https://trello.com/c/z5KvKA4D
=> import script for Redcar & Cleveland

polling_stations/apps/data_collection/data_types.py
These two conditions always need a manual check/follow-up
=> log some more warnings

polling_stations/apps/data_collection/management/commands/import_wokingham.py
=> remove election ID from Wokingham

polling_stations/apps/data_collection/management/commands/import_burnley.py
wait on https://trello.com/c/5PoRAEca
=> import Burnley

polling_stations/apps/addressbase/management/commands/create_blacklist.py
I overlooked this in #1455 which is causing postcodes which straddle (or used to straddle) boundaries in areas with structural changes to throw a 500. e.g: https://wheredoivote.co.uk/multiple_councils/BH80EE/
https://sentry.io/organizations/democracy-club-gp/issues/919785297/
=> use new local auth codes in blacklist table

polling_stations/apps/data_collection/management/commands/import_lewes.py
=> update Lewes import script

polling_stations/apps/data_collection/management/commands/misc_fixes.py
I'm collating a list of these to report to OS in due-course, but based on past experience, reporting problems now isnt going to get corrections into a release we can use for May. For now, we'll just cowboy it..
=> remove some problematic UPRNs from AddressBase

polling_stations/apps/data_collection/management/commands/import_westberks.py
wait on https://trello.com/c/Qzy8CCUq
=> import West Berkshire

polling_stations/apps/data_collection/management/commands/import_kingston-upon-hull.py
I think some addresses may be listed wrong. 
Trello card here: https://trello.com/c/to8j6d0R
=> import Kingston upon Hull

polling_stations/apps/data_collection/management/commands/import_warwick.py
Need to double check postcodes with LA.
=> Import script for Warwick (closes  #1598)

polling_stations/apps/data_collection/management/commands/import_st_helens.py
=> WiP: Import script for St Helens (closes #1684)

polling_stations/apps/data_collection/management/commands/import_brighton_hove.py
=> WiP: Import script for Brighton and Hove (closes #1688)

polling_stations/apps/data_collection/management/commands/import_three_rivers.py
=> Import script for Three Rivers (closes #1712)

polling_stations/apps/data_collection/management/commands/import_rossendale.py
=> fix election id for Rossendale

polling_stations/templates/fragments/no_election.html, polling_stations/templates/fragments/polling_station_known.html, polling_stations/templates/fragments/register_to_vote.html
Various text changes clarifying 2 May locals / 23 May Euros situation.
Intended for deploy after notice of election docs are published on Monday
also closes #1665
=> text edits for European Parl elections

polling_stations/apps/data_collection/management/commands/import_craven.py
=> Import craven

polling_stations/apps/data_collection/management/commands/import_winchester.py
=> Import script for Winchester  (closes #1778)

polling_stations/apps/data_collection/management/commands/import_torbay.py
=> Import script for Torbay (closes #1767)

polling_stations/apps/data_collection/management/commands/import_rochford.py
=> Import script for Rochford (closes #1791)

polling_stations/apps/data_collection/management/commands/import_cherwell.py
Issue: https://trello.com/c/dFiVcYob
=> Import script for Cherwell (closes #1731)

polling_stations/apps/data_collection/management/commands/import_newcastle_upon_tyne.py
=> Import script for Newcastle-upon-Tyne (closes #1792)

polling_stations/apps/data_collection/management/commands/import_south_cambridge.py
=> Import script for South Cambridgeshire (closes #1820)

polling_stations/apps/data_collection/management/commands/import_rotherham.py
This is a script for Euros. There is a tsv for the locals on S3 but it only has ~2500 records, so assume we're either waiting for more, or not doing it.
=> Import script for Rotherham (closes #1825)

polling_stations/apps/data_collection/management/commands/import_mole_valley.py
=> Import mole valley

polling_stations/apps/data_collection/management/commands/import_chichester.py
=> Import script for Chichester (closes #1754)

polling_stations/apps/data_collection/management/commands/misc_fixes.py
=> Council fixes 0630

polling_stations/apps/data_collection/management/commands/misc_fixes.py
Where I'm currently pushing fixes as they come in. Please ping me if you merge it.
=> Grid ref fixes

polling_stations/apps/data_collection/management/commands/import.py
This should speed batch imports up a bit by not caring about ordering
=> use starmap_async

polling_stations/apps/data_collection/management/commands/import_maidstone.py
Polling stations are not the same between locals and Euro elections, so two imports will be needed. This branch is for the European Parliament elections so should only be merged once the locals are complete.
Also we're waiting on corrections:
https://trello.com/c/TlchKxBj/84-maidstone
=> Import script for Maidstone European Elections (closes #1821)

polling_stations/templates/fragments/register_to_vote.html, polling_stations/templates/postcode_view.html
=> remove 'register to vote' content

polling_stations/apps/data_collection/management/commands/import_wandsworth.py
https://trello.com/c/Lx7GkCyM/87-wandsworth
=> Import script for Wandsworth (closes #1832)

polling_stations/apps/data_collection/management/commands/import_croydon.py, polling_stations/apps/data_collection/management/commands/misc_fixes.py
https://trello.com/c/htLwYd27/85-croydon
=> Import script for Croydon (closes #1830)

polling_stations/apps/data_collection/management/commands/import_bassetlaw.py
https://trello.com/c/2PPWXPcf/115-bassetlaw
=> Import script for Bassetlaw (closes #1849)

polling_stations/apps/data_collection/management/commands/import_shropshire.py
https://trello.com/c/Gbuq8yrr/123-shropshire
=> Import script for Shropshire (closes #1887)

polling_stations/apps/data_collection/management/commands/import_bedford.py, polling_stations/apps/data_collection/management/commands/import_bracknell_forest.py, polling_stations/apps/data_collection/management/commands/import_corby.py, polling_stations/apps/data_collection/management/commands/import_fareham.py, polling_stations/apps/data_collection/management/commands/import_folkestone_hythe.py, polling_stations/apps/data_collection/management/commands/import_hounslow.py, polling_stations/apps/data_collection/management/commands/import_huntingdonshire.py, polling_stations/apps/data_collection/management/commands/import_isle_of_wight.py, polling_stations/apps/data_collection/management/commands/import_milton_keynes.py, polling_stations/apps/data_collection/management/commands/import_wycombe.py
=> Import scripts 20190510

polling_stations/apps/data_collection/data_types.py
=> if match_quality is too low, remove the UPRN

polling_stations/apps/data_collection/management/commands/import_daventry.py, polling_stations/apps/data_collection/management/commands/misc_fixes.py
=> Import Daventry & update misc_fixes 

polling_stations/apps/data_collection/management/commands/import_west_devon.py
https://trello.com/c/ggbL8Mly/112-west-devon
=> import script for West Devon (closes #1848)

polling_stations/apps/data_collection/management/commands/import_eilean_siar.py, polling_stations/apps/data_collection/management/commands/import_perth_and_kinross.py, polling_stations/apps/data_collection/management/commands/import_south_ayrshire.py, polling_stations/apps/data_collection/management/commands/import_south_lanarkshire.py, polling_stations/apps/data_collection/management/commands/import_stirling.py, polling_stations/apps/data_collection/management/commands/import_west_lothian.py
This is ready for review, but relies on the change made in 914b1ef which is in #1996, so that should go in first.
Don't think there should be any merge conflicts but bounce it back if there are.
=> Import scripts scotland 20190517

polling_stations/apps/data_collection/management/commands/import_cheshire_west.py
=> Import script for Cheshire West and Chester (closes #1847)

polling_stations/apps/data_collection/management/commands/import_south_ayrshire.py
use data from http://maps-south-ayrshire.opendata.arcgis.com/ in preference to SpatialHub
=> switch South Ayrshire to use API

polling_stations/apps/data_collection/management/commands/import_orkney_islands.py
=> remove election id from orkney

polling_stations/apps/data_collection/management/commands/misc_fixes.py
=> update Chelmsford phone no

polling_stations/apps/data_collection/management/commands/import_wolverhampton.py
doing their homework the night before :mortar_board:
=> last minute Wolverhampton import

requirements/base.txt
doing all this in one PR so I only need to clear travis' dependency cache once
closes #2053
closes #2054
closes #2055
closes #2056
closes #2057
closes #2058
=> upgrade lots of dependencies

polling_stations/apps/councils/data/england-wales.csv
=> Update Barnet and Cardiff phone numbers

polling_stations/apps/data_finder/helpers/every_election.py, polling_stations/apps/data_finder/tests/test_ee_wrapper.py, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-my-address-not-in-list/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-northern-ireland/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-invalid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-with-address-picker-valid-station-id/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-check-postcodes/scenario-check-postcode-without-address-picker/then-i-submit-the-only-form.yaml, test_data/vcr_cassettes/integration_tests/feature-smoke-tests/scenario-check-example-page/given-i-visit-httplocalhostexample.yaml
Refs https://github.com/DemocracyClub/EveryElection/pull/597
=> request elections from EE which are both current AND future

polling_stations/apps/data_collection/management/commands/misc_fixes.py
these are fixed in the September Addressbase release
=> remove some redundant misc_fixes

polling_stations/apps/councils/data/scotland-vjbs.csv
=> Update Moray Division phone number

polling_stations/apps/data_collection/management/commands/import_hyndburn.py
The data on this was a it hairy…
Closes #2137
=> Import Hyndburn

polling_stations/apps/data_collection/management/commands/import_bassetlaw.py
With the `allow_station_point_from_postcode = False` flag this has only one location for a station. Not sure if this is ok or not.
=> Import script for bassetlaw (closes #2129)

polling_stations/apps/data_collection/management/commands/import_denbighshire.py
=> Import Denbighshire

polling_stations/apps/data_collection/management/commands/import_kettering.py
I think there are a few AddressBase issues in here
Closes #2154
=> Import Kettering

polling_stations/apps/dashboard/templates/dashboard/council_detail.html, polling_stations/apps/dashboard/templates/dashboard/postcode.html, polling_stations/apps/dashboard/views.py
couple more minor additions as I'm using it more
=> dashboard tweaks

polling_stations/apps/data_collection/management/commands/import_st_helens.py
=> Import script for St Helens (closes #2124)

polling_stations/apps/data_collection/management/commands/import_enfield.py
Definitely some dodgy addresses still here, but I don't think any of them are disrupting what the user sees, so left them for now.
=> Import script for Enfield (closes #2158)

polling_stations/apps/data_collection/management/commands/import_chichester.py
=> import Chichester

polling_stations/apps/data_collection/management/commands/import_gloucester.py
Notes:
* The postcode fix for 294 Painswick Road has made it upstream.
=> Import Gloucester (closes #2209)

polling_stations/apps/data_collection/management/commands/import_gedling.py
I'm not too sure what to do with the stray properties for which this currently returns `None`. A second pair of eyes here would be very useful!
=> Import Gedling (closes #2225)

polling_stations/templates/fragments/register_to_vote.html, polling_stations/templates/postcode_view.html
=> Revert "add registration content/deadline"

polling_stations/apps/data_collection/management/commands/import_adur.py, polling_stations/apps/data_collection/management/commands/import_cambridge.py, polling_stations/apps/data_collection/management/commands/import_dorset.py, polling_stations/apps/data_collection/management/commands/import_east_cambridgeshire.py, polling_stations/apps/data_collection/management/commands/import_kensington_and_chelsea.py, polling_stations/apps/data_collection/management/commands/import_south_lakeland.py, polling_stations/apps/data_collection/management/commands/import_southwark.py, polling_stations/apps/data_collection/management/commands/import_telford.py, polling_stations/apps/data_collection/management/commands/import_test_valley.py, polling_stations/apps/data_collection/management/commands/import_wealden.py, polling_stations/apps/data_collection/management/commands/import_worthing.py
=> Import scripts 20191128

polling_stations/apps/data_collection/management/commands/import_solihull.py
=> Import Solihull (closes #2404)

polling_stations/apps/data_collection/management/commands/import_bromsgrove.py, polling_stations/apps/data_collection/management/commands/import_croydon.py, polling_stations/apps/data_collection/management/commands/import_knowsley.py, polling_stations/apps/data_collection/management/commands/import_portsmouth.py, polling_stations/apps/data_collection/management/commands/import_rochford.py, polling_stations/apps/data_collection/management/commands/import_ryedale.py
NB in polling_stations/apps/data_collection/management/commands/import_croydon.py I deleted all the postcodes for the stations, as these appear in the address and we're not using the postcodes to geocode them anyway. This saved me looking up all the codes in the Euros file and then the GE file. If they do need updating for some reason let me know :+1:
=> Import scripts 20191203

polling_stations/apps/data_finder/views.py, polling_stations/templates/home.html
Front-page content for 12 Dec 2019.
=> GE-specific front page content

polling_stations/apps/data_collection/management/commands/import_wyre_forest.py
There might be some confusion around postcodes DY103ND, DY104ND and DY103NN,
but the offending property (100120753042) is in a split postcode, so it's not
going to mislead anyone.
=> Import Wyre Forest (closes #2403)

polling_stations/apps/data_collection/management/commands/import_dudley.py
Missing data for Coseley. Raised in Trello
=> Import Dudley (closes #2473)

polling_stations/apps/data_collection/management/commands/import_brighton_hove.py, polling_stations/apps/data_collection/management/commands/import_east_staffs.py, polling_stations/apps/data_collection/management/commands/import_guildford.py, polling_stations/apps/data_collection/management/commands/import_leeds.py, polling_stations/apps/data_collection/management/commands/import_pendle.py, polling_stations/apps/data_collection/management/commands/import_rochford.py, polling_stations/apps/data_collection/management/commands/import_thanet.py
various user/council-reported errors
=> pile of corrections

requirements/base.txt
- update marshmallow, boto3
- silence boto3 minor updates
=> package updates

polling_stations/apps/data_collection/management/commands/import.py
This should make it slightly easier to keep track of which new data has gone up on each deploy.
=> output GSS code in bulk import summary

package-lock.json, package.json, polling_stations/apps/dashboard/templates/dashboard/postcode.html, polling_stations/settings/static_files.py
Need to think about whether this is useful. At the moment it indiscriminately clusters everything. I ideally it would only cluster markers of the same type (i.e. by pollingstation group),  and I think the threshold needs to be reduced. 
Anyway parking this here for now.
=> Dashboard marker clusters

polling_stations/apps/data_collection/management/commands/import_crawley.py, polling_stations/apps/data_collection/management/commands/import_dacorum.py, polling_stations/apps/data_collection/management/commands/import_fareham.py, polling_stations/apps/data_collection/management/commands/import_rushmoor.py, polling_stations/apps/data_collection/management/commands/import_sedgemoor.py, polling_stations/apps/data_collection/management/commands/import_walsall.py
These need to be checked against new addressbase
=> Imports 20200228

polling_stations/apps/data_collection/data_types.py, polling_stations/apps/data_collection/tests/test_address_list.py
Just parking this here for now. It was a stab at beginning to tackle #2553 By getting a suggestion from addressbase where we could. However when I started thinking about testing it I realised that there's some duplication/overlap with the `handle_invalid_uprns method`. 
Any drive by comments welcome, but currently planning to rethink the approach.
=> Attempt to use addressbase data to correct invalid postcodes

polling_stations/templates/base.html, polling_stations/templates/base_full.html, polling_stations/templates/fragments/polling_station_known.html, polling_stations/templates/fragments/polling_station_unknown.html, polling_stations/templates/fragments/register_to_vote.html, requirements/base.txt
* Coronavirus-specific text
* Revert all May elections text edits
=> Text Edits

polling_stations/apps/councils/data/england-wales.csv
Refs https://trello.com/c/aJx5IxKh
What I've done here is just kept them as 4 separate councils in the DB (using the old GSS codes) but set the name of all 4 councils to "Buckinghamshire Council" (but with different email/phone/etc). This will achieve what we want for now.
=> contact details updates for Buckinghamshire

.circleci/config.yml, polling_stations/settings/base.py, polling_stations/settings/ci.py, polling_stations/settings/testing.py
As suggested here: https://github.com/DemocracyClub/EveryElection/pull/930#issuecomment-747552394
Thanks @chris48s
=> Make CI check for missing migrations

polling_stations/apps/addressbase/tests/factories.py, polling_stations/apps/addressbase/tests/test_factories.py, polling_stations/apps/councils/tests/factories.py, polling_stations/apps/councils/tests/test_factories.py, polling_stations/apps/pollingstations/tests/factories.py, polling_stations/apps/pollingstations/tests/test_factories.py, requirements/testing.txt
This is an initial pass at adding some factories and writing a couple of tests with them. 
My next step is to see if I can come up with some pattern for building out all the different scenarios we want to cover in the data_finder module which is one of the two apps where fixture management is complicated.
=> WiP: Factories

polling_stations/apps/data_finder/helpers/every_election.py, polling_stations/apps/data_finder/tests/test_ee_wrapper.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/pollingstations/context_processors.py, polling_stations/templates/base_full.html, polling_stations/templates/fragments/contact_details.html, polling_stations/templates/fragments/help_your_council.html, polling_stations/templates/fragments/ical_feed.html, polling_stations/templates/fragments/info_on_your_candidates.html, polling_stations/templates/fragments/multiple_elections.html, polling_stations/templates/fragments/polling_station_known.html, polling_stations/templates/fragments/polling_station_unknown.html, polling_stations/templates/fragments/register_to_vote.html, polling_stations/templates/fragments/you_dont_need_poll_card.html, polling_stations/templates/home.html, polling_stations/templates/postcode_view.html
This takes care of the tasks mentioned [here](https://github.com/DemocracyClub/UK-Polling-Stations/wiki/Maintenance-tasks#pre-election), and also adds a card about offering working for the council.
The wording of the latter probably needs some work.
I've deployed this to staging, in case anyone wants a look.
=> Pre election copy changes

polling_stations/apps/data_importers/management/commands/import_malvern_hills.py
Just one change; removing an address.
=> import script for malvern hills (closes #3090)

polling_stations/templates/fragments/register_to_vote.html
Source: https://www.electoralcommission.org.uk/i-am-a/voter/register-vote-and-update-your-details
I've manually fixed this on the current prod server.
=> Correct register to vote deadline

polling_stations/apps/data_importers/management/commands/import_burnley.py
This branch failed `pytest --flakes` on local machine
=> import script for burnley (closes #3147)

polling_stations/templates/fragments/multiple_elections.html, polling_stations/templates/fragments/register_to_vote.html
Three small things:
* Force emoji presentation on both ballot box characters
* Improve "More than one!" text to make more sense in context
* Fix the day of the week for April 19th.
=> Multiple polls text

polling_stations/apps/data_importers/management/commands/import_bradford.py
This branch failed `pytest --flakes` on local machine.
=> import script for bradford (closes #3150)

polling_stations/apps/data_importers/management/commands/import_huntingdonshire.py
34 polling stations without a postcode, coordinates or UPRN.
=> import script for huntingdonshire (closes #3189)

polling_stations/apps/data_importers/management/commands/import_leeds.py
The data required a lot of amendments. A second pair of eyes may be useful for this one.
=> import script for leeds (closes #3250)

polling_stations/apps/data_importers/management/commands/import_darlington.py
Changed from a coord to a postcode fix for consistency.
=> import script for darlington (closes #3258)

polling_stations/apps/data_importers/management/commands/import_north_east_lincs.py
Almost perfect; one query: https://trello.com/c/kXIT1oFl/380-north-east-lincolnshire
=> Import North East Lincs (closes #3156)

polling_stations/apps/data_importers/management/commands/import_stevenage.py
On hold while we wait on https://trello.com/c/5gWxFAJw/369-stevenage
=> Import Stevenage (closes #3121)

polling_stations/apps/data_importers/management/commands/import_eden.py
iniital wrangling done; waiting for more polling station address data
=> Import Eden (closes #3121)

polling_stations/apps/data_importers/management/commands/import_westminster.py
Waiting on https://trello.com/c/HpRDeeyv/401-westminster
=> Import Westminster (closes #3422)

locale/cy/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po, polling_stations/apps/councils/models.py, polling_stations/i18n/cy.py, polling_stations/management/commands/compilemessages.py, polling_stations/settings/base.py, polling_stations/templates/custom_finder.html, polling_stations/templates/fragments/cancelled_election.html, polling_stations/templates/fragments/contact_details.html, polling_stations/templates/fragments/help_your_council.html, polling_stations/templates/fragments/no_election.html, polling_stations/templates/fragments/polling_station_unknown.html, polling_stations/templates/multiple_councils.html, polling_stations/templatetags/i18n_with_welsh.py
I mismerged this earlier (#3204), so trying again.
=> Welsh council names

locale/cy/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po, polling_stations/apps/bug_reports/forms.py, polling_stations/apps/bug_reports/templates/bug_reports/report_form_inline.html, polling_stations/apps/bug_reports/templates/bug_reports/report_form_view.html, polling_stations/apps/data_finder/forms.py, polling_stations/apps/feedback/forms.py, polling_stations/apps/feedback/models.py, polling_stations/apps/feedback/templates/feedback/feedback_form.html, polling_stations/templates/fragments/feedback_js.html
Some bits I missed out on my original pass, including the "Enter your postcode" on the home page.
=> Translations for form text

polling_stations/apps/data_importers/management/commands/import_forest_of_dean.py
Not sure about the second polling station `._replace`…
=> Import Forest of Dean

polling_stations/apps/data_importers/management/commands/import_york.py
=> Updates for York

polling_stations/apps/data_importers/management/commands/import_halton.py
There were a few things wrong with multiple stations and I've dropped what I think is wrong. I have put up a Trello card, but let me know if this should be changed to a draft and fixed if they get back to us.
=> import script for halton (closes #3349)

polling_stations/templates/base_full.html
Co-authored-by: Virginia Dooley <vcdooley@gmail.com>
=> Improve twitter card image size

polling_stations/apps/data_importers/management/commands/import_merthyr.py
Yes, I know I've gone above and beyond in finding correct postcodes…
Corrections reported to council at https://trello.com/c/vyyTcnae/467-merthyr-tydfil
=> Import Merthyr Tydfil (closes #3412)

polling_stations/apps/data_importers/management/commands/import_brighton_hove.py
> UPRNS ASSIGNED STATION ID        : 137829
>  - As % of uprns in addressbase  : 85.5%
>  - As % of rows in council csv   : 87.0%
Looks a bit low, but probably fine?
=> Import Brighton and Hove (closes #3430)

polling_stations/apps/data_finder/helpers/routing.py
We want to know all the councils for a postcode, so that we know if the
postcode is split over council boundaries. Previously we were doing a
lookup per UPRN in the postcode. In postcodes with lots of UPRNs this is
very slow. This means there is one query for the whole postcode.
=> Improve routing helper performance

polling_stations/apps/data_finder/views.py
This changes the sort order of the addresspicker to show those addresses
with a station first.
=> Show addresses with a station first in addresspicker

polling_stations/apps/data_importers/management/commands/import_sheffield.py
https://trello.com/c/cSyJbFjn/473-sheffield
=> Sheffield fixes from council (closes #3757)

polling_stations/apps/data_importers/management/commands/import_south_norfolk.py, polling_stations/apps/data_importers/management/commands/misc_fixes.py
Point and address don't correspond
=> Remove points for Long Stratton Station

polling_stations/apps/councils/management/commands/import_councils.py, polling_stations/apps/councils/tests/test_council_importer.py, polling_stations/settings/constants/councils.py
- Change the gss field name.
- Hacks around Bucks till EC-API catches up.
=> Update council importer for 2021

package-lock.json, package.json, polling_stations/apps/file_uploads/templates/file_uploads/upload.html, polling_stations/apps/file_uploads/views.py, polling_stations/settings/static_files.py, polling_stations/templates/api_docs/api_base_template.html, polling_stations/templates/base.html, polling_stations/templates/fragments/feedback_js.html
Ref #4053
This work adds[ `promise-polyfill` ](https://www.npmjs.com/package/promise-polyfill)and makes `Promise` available in IE11. 
Confirmed with s3 upload `2022-02-07 18:54:41    8611211 ABD/2022-05-05/2022-02-07T18:54:39.429722/wdiv-upload-test.tsv`
=> Hotfix/Promises in IE11

polling_stations/apps/file_uploads/urls.py
Because I always forget the URL
=> Redirect from root URL to something useful

polling_stations/apps/file_uploads/templates/file_uploads/about.html
=> Remove duplicate text

polling_stations/apps/file_uploads/views.py
We sometimes import stations for a council when there are no real
addresses assigned - often labelled for 'OTHER ELECTORS' or similar.
We should handle this gracefully, in this case by ignoring those
stations.
=> Handle stations with no addresses

package-lock.json, polling_stations/apps/councils/management/commands/import_councils.py, polling_stations/apps/data_importers/base_importers.py, polling_stations/apps/data_importers/data_quality_report.py, polling_stations/apps/data_importers/management/commands/import_eoni.py, polling_stations/apps/pollingstations/models.py, polling_stations/settings/constants/councils.py, polling_stations/templates/api_docs/blueprints/finder.apibp, polling_stations/templates/base.html, polling_stations/templates/fragments/polling_station_unknown.html, polling_stations/templates/postcode_view.html
=> Import EONI data

polling_stations/apps/data_importers/management/commands/import_eoni.py
This allows us to process a csv that has already been reprojected
=> Add an flag to import_eoni indictating 4326 coords available

polling_stations/apps/data_importers/management/commands/import_gwynedd.py
=> Fix for Gwynedd

.github/dependabot.yml
This PR removes a blank object and attempts to fix [this failure](https://github.com/DemocracyClub/UK-Polling-Stations/runs/10846525702).
=> Remove extra -

polling_stations/templates/fragments/contact_details.html
Closes https://github.com/DemocracyClub/UK-Polling-Stations/issues/4832
=> Add council website to contact card

polling_stations/templates/custom_finder.html
Closes #4957 
Just a bit of a dodgy reference to council phone number, no biggie :)
=> Fix reference to council phone no

.github/dependabot.yml, polling_stations/apps/file_uploads/templates/file_uploads/council_login.html, polling_stations/assets/scss/style.scss
Ref https://github.com/DemocracyClub/dc_django_utils/pull/49
I've also centered the error just for postcode searches and removed duplicate error messages which are handled in `dc_utils`.
Before
After
Before
After
=> Fix error formatting

polling_stations/apps/data_importers/s3wrapper.py
See https://github.com/boto/boto/issues/2836
=> Allow importing from S3 buckets with dotted paths

polling_stations/apps/data_importers/management/commands/import_stratford-on-avon.py
PR triggered by upload at https://github.com/DemocracyClub/UK-Polling-Stations/issues/5112
=> Import script for Stratford on Avon (2023-05-04) (closes #5112)

cdk/stacks/wdiv_stack.py, deploy/files/scripts/postgres_reads_config.sh
* Tune postgres a little more
* Document instances used
=> Post load testing

polling_stations/apps/data_importers/management/commands/import_south_staffs.py
PR triggered by https://github.com/DemocracyClub/UK-Polling-Stations/issues/5345
=> Import script for South Staffordshire (2023-05-04) (closes #5345)

polling_stations/apps/addressbase/management/commands/split_and_load_csv_to_database.py, polling_stations/settings/constants/db.py
Downloads data from S3, splits it in to chunks and loads it into Postgres using n processes.
=> Script to bulk COPY data in to Postgres

polling_stations/apps/data_importers/management/commands/import_dudley.py
PR triggered by https://github.com/DemocracyClub/UK-Polling-Stations/issues/5384
=> Import script for Dudley (2023-05-04) (closes #5384)

polling_stations/apps/data_importers/management/commands/import_warwick.py
=> Import script for Warwick (2023-05-04) (closes #5401)

polling_stations/settings/base.py, polling_stations/templates/election_explainers.html, polling_stations/templates/fragments/cancelled_election.html, polling_stations/templatetags/markdown_filter.py
Spent 15mins trying to get a playwright test to work and failed, however this fixes it locally for me. I am confused about whether this has been broken for a long time though.
I think this has been removed (unitentionally?) from dc_django_utils in this [commit](https://github.com/DemocracyClub/dc_django_utils/commit/698ddc54d79cfcd9b21a1293bf617f39f8a78d3d). 
This puts it back as a stop gap.
=> Fix markdown filter

polling_stations/apps/data_importers/management/commands/import_ipswich.py
PR triggered by https://github.com/DemocracyClub/UK-Polling-Stations/issues/5540
=> Import script for Ipswich (2023-05-04) (closes #5540)

polling_stations/apps/data_importers/management/commands/import_torridge.py
PR triggered by https://github.com/DemocracyClub/UK-Polling-Stations/issues/5489
=> Import script for Torridge (2023-05-04) (closes #5489)

polling_stations/apps/data_importers/management/commands/import_preston.py
PR Triggered by https://github.com/DemocracyClub/UK-Polling-Stations/issues/5585
=> Import script for Preston (2023-05-04) (closes #5585)

polling_stations/apps/data_importers/management/commands/import_knowsley.py
PR triggered by https://github.com/DemocracyClub/UK-Polling-Stations/issues/5520
=> Import script for Knowsley (2023-05-04) (closes #5520)

polling_stations/apps/data_importers/management/commands/import_harborough.py
PR triggered by https://github.com/DemocracyClub/UK-Polling-Stations/issues/5536
=> Import script for Harborough (2023-05-04) (closes #5536)

polling_stations/apps/data_importers/management/commands/import_telford.py
=> Import script for Telford and Wrekin (2023-05-04) (closes #5629)

polling_stations/apps/data_importers/management/commands/import_gedling.py
=> Import script for Gedling (2023-05-04) (closes #5637)

polling_stations/apps/data_importers/management/commands/import_cotswold.py
Trello card: https://trello.com/c/8IESf1K3/644-cotswold
=> Add station locations to Cotswold

polling_stations/apps/data_importers/management/commands/import_mid_sussex.py
=> Import script for Mid Sussex (2023-05-04) (closes #5653)

polling_stations/apps/data_importers/management/commands/import_west_oxfordshire.py
Trello ticket: https://trello.com/c/hJlCMzjl/642-west-oxen
=> Add station locations to West Oxfordshire

polling_stations/apps/data_importers/management/commands/import_southend.py
Trello ticket: https://trello.com/c/4jCm9m4a/634-southend
=> Add station locations to Southend

polling_stations/apps/data_importers/management/commands/import_new_forest.py
Trello ticket: https://trello.com/c/9gSiDVoz/631-new-forest
=> Add station locations to New Forest

polling_stations/apps/data_importers/management/commands/import_reading.py
Trello ticket: https://trello.com/c/Q772H582/674-reading
=> Add station locations to Reading

polling_stations/apps/data_finder/helpers/every_election.py
imported `datetime` lib to namespace `datetime` and `date` classes, so as not to shadow vars called `date`.
=> Compare dates when checking ballots for poll day

polling_stations/templates/api_docs/blueprints/data_structures.apibp
=> Update API docs with cancelled reason

polling_stations/assets/custom_js/map.js, polling_stations/templates/base.html
A couple of minor fixes for accessibility I found when reviewing the site in lighthouse
=> Lighthouse fixes

.circleci/deploy-config.yml, cdk/lambdas/wdiv-s3-trigger/tests/test_handler.py, cdk/lambdas/wdiv-s3-trigger/trigger/handler.py
Have made the change to the lambda function in the console, and it fixes the issue.
~However introduces a bunch of test failures around length of `response.calls`~
=> API key Env Var hasn't changed name

polling_stations/apps/data_importers/management/commands/import_newcastle_upon_tyne.py, polling_stations/apps/file_uploads/views.py
Resolves https://democracy-club-gp.sentry.io/issues/4935122110/?project=4504713373876224&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
---
- https://app.asana.com/0/0/1206598867276500
=> Redirect to login page if no auth token in GET params

polling_stations/apps/data_importers/management/commands/import_babergh.py
station change from babergh & mid suffolk council - the station in question is in babergh and is excluded in the mid-suffolk script so have only changed babergh.
=> station change from babergh & mid suffolk council

polling_stations/apps/data_importers/management/commands/import_wrexham.py
Changes requested by the council: https://app.asana.com/0/1205951895246773/1206703288014763
=> Wrexham - fix for council election-date

polling_stations/apps/data_importers/management/commands/import_northumberland.py
Changes requested by the council: https://app.asana.com/0/1205951895246773/1206793505760767
=> Northumberland - fix for council election-date

polling_stations/apps/data_importers/management/commands/import_brighton_hove.py
Polling station change requested by the council:
https://app.asana.com/0/inbox/1206637811800210/1206839613770915/1206866691794255
=> fix for brighton-and-hove 2024-05-02

polling_stations/apps/file_uploads/models.py
https://democracy-club-gp.sentry.io/issues/4925452960/?project=4504713373876224&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=3#
=> Have a sleep if 409 on push to gh

polling_stations/apps/file_uploads/templates/file_uploads/file_detail.html
=> Show csv rows on file detail page

polling_stations/apps/file_uploads/templates/file_uploads/council_detail.html
Links to: https://democracyclub.org.uk/projects/polling-stations/upload/
---
- https://app.asana.com/0/0/1206895894364640
=> Change location to map and include link to info

polling_stations/apps/data_importers/management/commands/import_gateshead.py
---
- https://app.asana.com/0/0/1206895895899070
=> fix for gateshead-2024-05-02

cdk/stacks/wdiv_stack.py
With latest EE, including `sync_elections` fix
=> Update EE AMI

polling_stations/apps/data_importers/management/commands/import_peterborough.py
---
- https://app.asana.com/0/0/1207098048523292
=> postcode correction from PTE council

polling_stations/apps/data_importers/management/commands/import_cambridge.py
---
- https://app.asana.com/0/0/1206918709115594
=> coords correction from CAB council

polling_stations/apps/data_importers/management/commands/import_stratford-on-avon.py
---
- https://app.asana.com/0/0/1207150982481911
=> station name fix from STR council

polling_stations/apps/data_importers/management/commands/import_haringey.py
---
- https://app.asana.com/0/0/1207148321422965
=> station fix from HRY council

polling_stations/apps/data_importers/management/commands/import_reigate_and_banstead.py
---
- https://app.asana.com/0/0/1207135633709888
=> station fix from REI council

polling_stations/apps/data_importers/management/commands/import_north_kesteven.py
Station change + added split postcodes
---
- https://app.asana.com/0/0/1207192195506358
=> station change from NKE council

polling_stations/apps/data_importers/management/commands/import_newham.py
---
- https://app.asana.com/0/0/1207204404536855
=> station change from NWM council

polling_stations/apps/data_importers/management/commands/import_derbyshire_dales.py
---
- https://app.asana.com/0/0/1207195036448111
=> station coord fix from DEB council

polling_stations/apps/data_importers/management/commands/import_breckland.py
---
- https://app.asana.com/0/0/1207212522906666
=> fix for bugreport 627 (BRE)

polling_stations/apps/data_importers/management/commands/import_rugby.py
---
- https://app.asana.com/0/0/1207213161209837
=> postcode correction from RUG council

polling_stations/apps/data_importers/management/commands/import_powys.py
---
- https://app.asana.com/0/0/1207218983751244
=> stations change from POW council

polling_stations/apps/data_importers/management/commands/import_wychavon.py
=> fix for bugreport 645 (WYC)

polling_stations/apps/data_importers/management/commands/import_liverpool.py
postcode source: https://www.stmarys-grassendale.co.uk/church-hall/
=> fix for bugreport 648 (LIV)

.circleci/deploy-config.yml, cdk/stacks/wdiv_stack.py
Not to be merged until the EE backup is finished
=> Add more instances to the pool

polling_stations/apps/data_importers/management/commands/import_eoni.py
Tiny PR to get the correct date on the servers
=> Change date for EONI importer

polling_stations/apps/data_finder/helpers/baked_data_helper.py, polling_stations/apps/data_finder/helpers/every_election.py
This isn't ideal, but there are slight differences between the JSON we have from WCIVF and the JSON we have from EE.
To save time, just take the EE JSON
We can resolve the other issues at a later date.
I've also tested this from a devs.DC call (locally), and passes the resulting devs.DC JSON through the response builder to validate that it's as expected.
=> Take ballot JSON from EE

.circleci/deploy-config.yml, cdk/stacks/wdiv_stack.py
With changes from https://github.com/DemocracyClub/EveryElection/pull/2159
=> Bump EE image

polling_stations/apps/data_importers/management/commands/import_hart.py
https://app.asana.com/0/1205951895246773/1207480499431583/f
=> adds coords for station from HAT council

polling_stations/apps/data_importers/management/commands/import_chorley.py
https://app.asana.com/0/1205951895246773/1207479146611240/f
=> station postcode updates from CHO council

polling_stations/apps/data_importers/management/commands/import_bcp.py
https://app.asana.com/0/1205951895246773/1207482836549784/f
=> station fixes from BCP council

polling_stations/apps/data_importers/management/commands/import_havant.py
https://app.asana.com/0/1205951895246773/1207512272217597/f
=> station coord change from HAA council

polling_stations/apps/data_importers/management/commands/import_vale_of_white_horse.py
https://app.asana.com/0/1205951895246773/1207549520638369/f
=> station amendment from VAL council

polling_stations/apps/data_importers/management/commands/import_caerphilly.py
https://app.asana.com/0/1205951895246773/1207538384516181/f
=> postcode fixes from CAY council

polling_stations/apps/data_importers/management/commands/import_worcester.py
https://app.asana.com/0/1205951895246773/1207525772053041/f
=> station change from WOC council

polling_stations/apps/data_importers/management/commands/import_kingston-upon-thames.py
https://app.asana.com/0/1205951895246773/1207561594130010/f
=> misc fixes for KTT council

polling_stations/apps/data_importers/management/commands/import_calderdale.py
https://app.asana.com/0/1205951895246773/1207575023138944/f
=> station coord fixes from CLD council

polling_stations/apps/data_importers/management/commands/import_pembrokeshire.py
https://app.asana.com/0/1205951895246773/1207591479254448/f
=> station change from PEM council

polling_stations/apps/data_importers/management/commands/import_warrington.py
https://app.asana.com/0/1205951895246773/1207573406343679/f
=> station coord update from WRT council

polling_stations/apps/data_importers/management/commands/import_south_lanarkshire.py
https://app.asana.com/0/1205951895246773/1207548649429367/f
=> station change from SLK council

polling_stations/apps/data_importers/management/commands/import_huntingdonshire.py
https://app.asana.com/0/1205951895246773/1207618105794100/f
=> station typo fix from HUN council

polling_stations/apps/data_importers/management/commands/import_rhondda_cynon_taf.py
https://app.asana.com/0/1205951895246773/1207611829621945/f
=> restores station postcodes for RCT council

polling_stations/apps/data_importers/management/commands/import_torbay.py
https://app.asana.com/0/1205951895246773/1207564509681486/f
=> station postcode fix for TOB council

polling_stations/apps/data_importers/management/commands/import_cheshire_west.py
=> fix CHW file path

polling_stations/apps/data_importers/management/commands/import_kingston-upon-thames.py
https://app.asana.com/0/1205951895246773/1207561594130010/f
=> station name change for KTT council

polling_stations/apps/data_importers/management/commands/import_fife.py
https://app.asana.com/0/1205951895246773/1207618395148616/f
=> station coord fixes from FIF council

polling_stations/apps/data_importers/management/commands/import_worthing.py
https://app.asana.com/0/1207538772343223/1207588331388506/f
=> bug report 666: removes map pending council response

polling_stations/apps/data_importers/management/commands/import_tendring.py
https://app.asana.com/0/1207538772343223/1207588335129208/f
=> station change from TEN council

polling_stations/apps/data_importers/management/commands/import_haringey.py
https://app.asana.com/0/1207538772343223/1207668448620484/f
=> fixes wrong coords for HRY station

polling_stations/apps/data_importers/management/commands/import_south_derbyshire.py
https://app.asana.com/0/1207538772343223/1207674775497025/f
=> freshdesk bug report: removes map pending response from SDE council

polling_stations/apps/data_importers/management/commands/import_south_derbyshire.py
https://app.asana.com/0/1207538772343223/1207674775497025/f
=> freshdesk bug report fix for SDE council

polling_stations/apps/data_importers/management/commands/import_manchester.py
https://app.asana.com/0/1205951895246773/1207674775497044/f
=> district station change from MAN council

polling_stations/apps/data_importers/management/commands/import_ealing.py
https://app.asana.com/0/1205951895246773/1207624161773545/f
=> restores station postcode for EAL council

polling_stations/apps/data_importers/management/commands/import_anglesey.py
https://app.asana.com/0/1205951895246773/1207637626303841/f
=> adds missing postcodes for AGY council

polling_stations/apps/data_importers/management/commands/import_fife.py
bug report 688: https://app.asana.com/0/1207538772343223/1207702297589407/f
=> bug report 688: removes map pending council response

polling_stations/apps/data_importers/management/commands/import_vale_of_glamorgan.py
https://app.asana.com/0/1207538772343223/1207702808010370/f
=> bugfix for WDIV bugreport #683

polling_stations/apps/data_importers/management/commands/import_aberdeenshire.py
https://app.asana.com/0/1207538772343223/1207664746659512/f
=> bugreport ~675: corrects station address for ABD council

polling_stations/apps/data_importers/management/commands/import_charnwood.py
https://app.asana.com/0/1207538772343223/1207714103388351/f
=> station change from CHA council

polling_stations/apps/data_importers/management/commands/import_amber_valley.py
https://app.asana.com/0/1207538772343223/1207724034376573/f
=> removes wrong station point for AMB council

polling_stations/apps/data_importers/management/commands/import_east_riding.py
https://app.asana.com/0/1207538772343223/1207724034376581/f
=> station change from ERY council

polling_stations/apps/data_importers/management/commands/import_west_dunbartonshire.py
https://app.asana.com/0/1207538772343223/1207724519362823/f
=> station address fix for WDU council

polling_stations/apps/data_importers/management/commands/import_birmingham.py
https://app.asana.com/0/1207538772343223/1207715238499486/f
=> fix location for BIR council station

polling_stations/apps/data_importers/management/commands/import_east_ayrshire.py
https://app.asana.com/0/1207538772343223/1207736883993741/f
=> removes wrong station point for EAY council

polling_stations/apps/data_importers/management/commands/import_brent.py
https://app.asana.com/0/1207538772343223/1207736836781430/f
=> removes wrong point for BEN council

polling_stations/apps/data_importers/management/commands/import_bedford.py
https://app.asana.com/0/1207538772343223/1207737037084540/f
=> removes wrong point for BDF council

polling_stations/apps/data_importers/management/commands/import_tonbridge.py
https://app.asana.com/0/1207538772343223/1207737405374420/f
=> station change from TON council

polling_stations/apps/data_importers/management/commands/import_camden.py
https://app.asana.com/0/1207538772343223/1207738396549540/f
=> removes wrong station point for CMD council

polling_stations/apps/data_importers/management/commands/import_greenwich.py
Refs
https://democracy-club-gp.sentry.io/issues/5978765100
https://github.com/DemocracyClub/UK-Polling-Stations/pull/8111
This is what polling bot spat out before failing to format the file
I've not done any QA on it though
=> import script for greenwich 2024-11-14

requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/testing.in, requirements/testing.txt
Fixes https://democracy-club-gp.sentry.io/issues/5978765100
I accidentally broke this in
- https://github.com/DemocracyClub/UK-Polling-Stations/commit/b426872f311fadccb1881ee46840b9b477646764
- https://github.com/DemocracyClub/UK-Polling-Stations/commit/f25f5a5a92afa5378ecb7467ebfd9ba68471cc3c
=> move ruff to prod requirements

polling_stations/apps/data_importers/management/commands/import_highland.py
=> Import script for Highland (2024-09-26) (closes #8121)

polling_stations/apps/data_finder/tests/test_geocoders.py
A little something I noticed while working on #8147
At some point we updated this code but not the comment
This fixes that bit of comment rot.
=> fix incorrect comment

polling_stations/settings/base.py
This PR implements a similar solution to https://github.com/DemocracyClub/EveryElection/pull/2311
Same vibes anyway
Again, I tested this works by setting a sentry DSN locally
=> silence sentry DisallowedHost errors

.circleci/deploy-config.yml, polling_stations/apps/addressbase/management/commands/update_addressbase.py, polling_stations/apps/addressbase/tests/test_update_addressbase.py, polling_stations/apps/data_finder/fixtures/integration_tests_addressbase.json, requirements/base.txt, requirements/constraints.txt, requirements/testing.txt
I've shoved this on dev environment and successfully imported onspd and addressbase.
Once this is merged we should run those commands.
=> Bump uk-geo-utils

polling_stations/apps/data_finder/helpers/every_election.py
Refs https://app.asana.com/0/1204880927741389/1208953917281175/f
As written, this was matching common council elections only, but not alderman elections
=> match both local.city-of-london and local.city-of-london-alder

cdk/stacks/command_runner_stack.py, polling_stations/apps/data_importers/management/commands/import_eoni.py, polling_stations/apps/data_importers/management/commands/import_eoni_from_s3.py
Last fix wasn't enough.
I've Just tried this out in dev env and it ran to completion.
=> Run import eoni as polling_stations user

polling_stations/apps/core/context_processors.py, polling_stations/apps/data_finder/tests/playwright/test_nav.py, polling_stations/assets/custom_css/map.css, polling_stations/assets/scss/style.scss, polling_stations/settings/base.py, polling_stations/settings/static_files.py, polling_stations/templates/base.html, polling_stations/templates/fragments/polling_station_known.html, requirements/base.in, requirements/base.txt, requirements/constraints.txt
Refs https://app.asana.com/0/1204880927741389/1208958646411291/f
This PR ties together a few of bits of work.
- Upgrade to design-system==0.7.0
- Upgrade to dc_django_utils==8.0.1
- Account for breaking changes in both releases
- Fix the underlines on the map +/- buttons (which if we zoom all the way out was the original point of this work)
- Update the footer to account for latest design-system/dc_django_utils's opinions on that
Screenshots
=> design system/django-utils upgrade

polling_stations/templates/fragments/ni_out_of_cycle_station.html
Overlooked this in https://github.com/DemocracyClub/UK-Polling-Stations/pull/8210
Whoops!
=> use correct map class for NI out of cycle

polling_stations/templates/fragments/generic_accessibility.html
https://app.asana.com/0/1204880927741389/1209201389125605/f
=> remove dead RNIB link

polling_stations/apps/data_importers/management/commands/import_buckinghamshire.py
station change from BUC council
---
- https://app.asana.com/0/0/1209485233589306
=> station change from BUC council

polling_stations/apps/pollingstations/models.py
fixes https://app.asana.com/0/1204880927741389/1209389148316515
=> replace ` with ' in addresses

polling_stations/templates/fragments/polling_station_unknown.html
=> link to city of london finder

polling_stations/apps/data_importers/management/commands/import_watford.py
---
- https://app.asana.com/0/0/1209555104960068
=> station change from WAT council

deploy/files/scripts/setup_db_replication.sh
=> fix trailing comma in replication setup

requirements/base.txt, requirements/constraints.txt, requirements/local.txt, requirements/production.txt, requirements/testing.txt
=> upgrade django==4.2.20

polling_stations/apps/data_importers/management/commands/import_wychavon.py
---
- https://app.asana.com/0/0/1209698599535917
=> adds station UPRNs from WYC council

polling_stations/apps/data_importers/management/commands/import_amber_valley.py, polling_stations/apps/data_importers/management/commands/import_derbyshire_dales.py, polling_stations/apps/data_importers/management/commands/import_durham.py, polling_stations/apps/data_importers/management/commands/import_hyndburn.py, polling_stations/apps/data_importers/management/commands/import_malvern_hills.py
---
- https://app.asana.com/0/0/1209698830860144
- https://app.asana.com/0/0/1209677486387818
- https://app.asana.com/0/0/1209677486387826
- https://app.asana.com/0/0/1209698599535940
=> various council corrections

polling_stations/apps/data_importers/management/commands/import_mansfield.py
---
- https://app.asana.com/0/0/1209698830860148
=> station postcodes from MAS council

deploy/files/scripts/user_scripts/sync_baked_elections_parquet.sh, polling_stations/settings/constants/elections.py
To be merged after https://github.com/DemocracyClub/UK-Polling-Stations/pull/8487 merged and env var set
=> Parquet golive

polling_stations/apps/data_importers/management/commands/import_amber_valley.py
---
- https://app.asana.com/0/0/1209810222317594
=> station fixes from AMB council

polling_stations/apps/data_importers/management/commands/import_cotswold.py
---
- https://app.asana.com/0/0/1209710889793139
=> station coords from COT council

polling_stations/apps/data_importers/management/commands/import_reigate_and_banstead.py
---
- https://app.asana.com/0/0/1209873073123384
=> station coords from REI council

polling_stations/apps/data_importers/management/commands/import_west_lindsey.py
---
- https://app.asana.com/0/0/1209868573975227
=> station coords from WLI council

polling_stations/apps/data_importers/management/commands/import_northumberland.py
---
- https://app.asana.com/0/0/1209974464473326
=> station change from NBL council

polling_stations/apps/data_importers/management/commands/import_thanet.py
---
- https://app.asana.com/0/0/1209986331419450
=> station postcode fix from THA council

.circleci/deploy-config.yml, cdk/stacks/wdiv_stack.py, polling_stations/settings/constants/elections.py
=> post-election shutdown

polling_stations/apps/data_finder/helpers/routing.py, polling_stations/apps/data_finder/middleware.py, polling_stations/apps/data_finder/review_views.py, polling_stations/apps/data_finder/tests/test_routing_helper.py, polling_stations/apps/data_finder/tests/test_views.py, polling_stations/apps/data_finder/views.py, polling_stations/apps/data_importers/management/commands/import_walsall.py, polling_stations/templates/fragments/postcode_form.html, polling_stations/templates/reviews/WLL/20250609/home.html, polling_stations/templates/reviews/WLL/20250609/polling_station_known.html, polling_stations/templates/reviews/WLL/20250609/postcode_view.html, polling_stations/urls.py
This PR implements experimental changes to allow us to show a custom search/results page for Walsall Council's upcoming review of polling stations
I've tried to minimise the changes to the core WDIV app to enable this, but inevitable I have had to make some. I've split things up so the changes to the core are in one commit and the Walsall specific stuff is separated.
=> Walsall polling districts review

polling_stations/apps/data_finder/views.py
Fixes https://democracy-club-gp.sentry.io/issues/6642804983
=> set namespace on MultipleCouncilsView
